### ISSUE TITLE
Tagbar is making Vim's cursor lag

### ISSUE THREAD

**Issue by charlax** [majutsushi/tagbar#107]
Hi,

After a few minutes of use, my Vim is getting very slow, even when something as simple as moving the cursor.

I profiled the running function and got this result:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    3   0.006288   0.002934  <SNR>79_AutoUpdate()
    3   0.003460   0.001882  xolox#easytags#autoload()
    3   0.002858   0.000117  <SNR>79_HighlightTag()
    3   0.002741   0.002732  <SNR>79_GetNearbyTag()
   15   0.001804             <SNR>44_Highlight_Matching_Pair()
    3   0.000657   0.000507  xolox#easytags#get_tagsfile()
   21   0.000559             xolox#misc#option#get()
    3   0.000361   0.000083  xolox#easytags#file_has_tags()
    6   0.000279   0.000088  <SNR>31_resolve()
    3   0.000252   0.000223  <SNR>79_IsValidFile()
   18   0.000191             <SNR>79_LogDebugMessage()
    3   0.000170             xolox#easytags#supported_filetypes()
    3   0.000157             <SNR>31_cache_tagged_files()
    9   0.000051             112()
    3   0.000017             114()
    3   0.000014             <SNR>31_create_context()
    3   0.000014             111()
    3   0.000009             110()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    3   0.006288   0.002934  <SNR>79_AutoUpdate()
    3   0.002741   0.002732  <SNR>79_GetNearbyTag()
    3   0.003460   0.001882  xolox#easytags#autoload()
   15              0.001804  <SNR>44_Highlight_Matching_Pair()
   21              0.000559  xolox#misc#option#get()
    3   0.000657   0.000507  xolox#easytags#get_tagsfile()
    3   0.000252   0.000223  <SNR>79_IsValidFile()
   18              0.000191  <SNR>79_LogDebugMessage()
    3              0.000170  xolox#easytags#supported_filetypes()
    3              0.000157  <SNR>31_cache_tagged_files()
    3   0.002858   0.000117  <SNR>79_HighlightTag()
    6   0.000279   0.000088  <SNR>31_resolve()
    3   0.000361   0.000083  xolox#easytags#file_has_tags()
    9              0.000051  112()
    3              0.000017  114()
    3              0.000014  <SNR>31_create_context()
```

So apparently TagBar and EasyTags are causing most of the lag.

Any Python file will make Vim slow, especially big ones. My vim dotfiles are here: https://github.com/charlax/dotvim

I did not change `updatetime`.

Thanks for your help!

**Comment by alerque** [comment]
It reading through the history here it sounds to me like EasyTags was the culprit. Enough time has passed that it might have been fixed. In any case I don't see a current issue that needs addressing in this plugin. If I'm wrong about that please feel free to comment here and I'm happy to re-open this and look into it.

The other performance related issue that I'll crosslink here in case people find this on search is #494, which has to do with the lag between buffer changes and tagbar updates. Different issue, but seems to be a common point of confusion.

**Comment by bam80** [comment]
@alerque Did you try with `xproto.h`? Any dependency on file size?

**Comment by alerque** [comment]
@bam80 [This comment](https://github.com/majutsushi/tagbar/issues/107#issuecomment-9401727) already details pretty much what can and can't be done about the edge case seen in `xproto.h`, and also explains the large file size. File size itself isn't even the issue, how many symbols they spit out is. But that isn't what this issue was about, this issue was opened for another reason and I don't see anything left related to that to track here.
