### ISSUE TITLE
Tagbar: Ctags doesn't seem to be Exuberant Ctags!

### ISSUE THREAD

**Issue by LxPvlv** [majutsushi/tagbar#237]
in .vimrc
let g:tagbar_ctags_bin ='/opt/fishman_ctags/bin/ctags'

\<F8\>
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
GNU ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'/opt/fishman_ctags/bin/ctags' --version"
Command output:
Fishman Ctags Development, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 19 2014, 07:45:26
  Addresses: <dhiebert@users.sourceforge.net>, https://github.com/fishman/ctags
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc

**Comment by majutsushi** [comment]
The name change has been reverted (see #226), so this can be closed.
