### ISSUE TITLE
sh: coffeetags: command not found

### ISSUE THREAD

**Issue by statico** [majutsushi/tagbar#241]
When trying to use this great-looking plugin with CoffeeTags, I ran into this:

```
2014-12-30 14:54:45.000551: Escaped ctags command: 'coffeetags'    '/var/folders/2g/3zgp6rzs1dn3m15rrfhcg6_40000gn/T/v9gNPXY/102.coffee'
2014-12-30 14:54:45.000647: Executing ctags command: 'coffeetags'    '/var/folders/2g/3zgp6rzs1dn3m15rrfhcg6_40000gn/T/v9gNPXY/102.coffee'
2014-12-30 14:54:45.027129: Calling shell to execute: "('coffeetags'    '/var/folders/2g/3zgp6rzs1dn3m15rrfhcg6_40000gn/T/v9gNPXY/102.coffee') >/var/folders/2g/3zgp6rzs1dn3m15rrfhcg6_40000gn/T/v9gNPXY/103 2>&1"
2014-12-30 14:54:45.048875: Command output:
2014-12-30 14:54:45.048998: sh: coffeetags: command not found
 2014-12-30 14:54:45.049461: Ctags error when processing file
```

Strangely, tagbar works fine in console Vim but this error occurs with MacVim.

The offending line seems to be this in `ExecuteCtags()` of `autoload/tagbar.vim`:

      if has('unix')
          " Reset shell in case it is set to something incompatible like fish
          let shell_save = &shell
          set shell=sh " <<<< HERE
      endif

My default shell is `/bin/zsh` (as reported by `:set shell` in MacVim). I modify `$PATH` in my .vimrc to include the path to `coffeetags` and other utilities. Commenting out that line in tagbar.vim makes everything work.

I have no idea what the right solution is here. If this is too vague or too much of a head-scratcher then feel free to close the issue. I figured I'd at least say something.

**Comment by majutsushi** [comment]
Your modified path doesn't seem to get propagated to the shell. I assume
that either the console version calls shells differently or the environment
that gets passed to the console version also includes the correct path,
whereas the MacVim environment does not.

Does it work for you if you replace the 'set shell' line with this?

    let &shell = "env PATH=" . $PATH . " sh"

If it doesn't then I'm not sure what the best solution would be, but an easy
fix would at least be to specify the full path to the coffeetags executable.
Putting the correct path into the system environment should also work, but I
don't know where MacVim gets its environment from.

**Comment by statico** [comment]
Weird. Just tried testing by reverting tagbar and I can't reproduce the problem.

Thanks for the ENV suggestion — I'll definitely give that a try if the problem crops up again.

Thanks for the awesome plugin!

**Comment by passabilities** [comment]
I am getting this error as well. What do you mean revert Tagbar? @statico

**Comment by statico** [comment]
@passabilities Unsure, it was a long time ago. I think I reverted back to a previous version of tagbar that I had installed. I no longer use this plugin.
