### ISSUE TITLE
Mouse Scrolling in vim in tmux

### ISSUE THREAD

**Issue by aharris88** [majutsushi/tagbar#243]
When I have this plugin installed it causing mouse scrolling issues in tmux. Normally I can scroll around inside of vim files inside of tmux just fine, but when this plugin is installed, I can only scroll down the file. When I try scrolling up the file, it scrolls up in tmux instead.

It may be related to Issue #107.

I'm using mac os x, vim version 7.4, and iTerm 2.

**Comment by majutsushi** [comment]
I'm not seeing the relation to #107, is that really the issue you wanted to refer to? As for this issue I'm afraid I'm not able to reproduce it, and I'm not sure how Tagbar could even be responsible for this, it hardly does anything with the mouse. What exactly do you mean by "installed", is it really enough to just be installed or does it have to be open? Does the same thing happen with NERDTree or even just a normal second window, or if you open Tagbar on the left side instead?

**Comment by aharris88** [comment]
I install vim plugins using vundle.

I install it by putting

    Plugin 'majutsushi/tagbar'

in my .vimrc, saving, sourcing my .vimrc, and running

    :PluginInstall

As soon as I install this plugin (, the scrolling issue shows up. I don't even have to open tagbar. Then to make it stop I have to remove that line from my .vimrc and run

    :PluginClean

And then I have to restart vim.

And I don't have the issue when I have other vim windows or panes or tabs.

Do you use vim inside of tmux?

**Comment by aharris88** [comment]
You're right, I finally was able to reproduce the issue without tagbar installed. Uninstalling tagbar seemed helped with most of the issue, but I'm still seeing it with some files.

**Comment by majutsushi** [comment]
Thanks for investigating, and sorry for the late reply. I was trying to think
of any connection between Tagbar and what you were seeing but couldn't come up
with anything. Good to know it doesn't seem to be related after all.
