### ISSUE TITLE
alternate window

### ISSUE THREAD

**Issue by Konfekt** [majutsushi/tagbar#244]
Hello, if you feel like it, comment on a new error appearing in latest Vim versions in your plugin with regard to the alternate window numbering: https://groups.google.com/d/msg/vim_dev/PFJkLtJu_nY/5ule85O3Q4gJ

**Comment by majutsushi** [comment]
Thanks for the heads-up, I'm rather behind in my mailing list reading. I see there are plans to change the Vim behaviour so the error won't appear any more, but it can't hurt to add a small workaround to Tagbar. If you can reproduce the issue, could you please have a quick try whether changing the line

```vim
let prevwinnr = winnr('#')
```

in the `QuitIfOnlyWindow()` function to

```vim
let prevwinnr = winnr('#') == 0 ? curwinnr : winnr('#')
```

fixes the issue? Thanks!

**Comment by Konfekt** [comment]
Yep that fixes it (but see my last comment at https://groups.google.com/d/msg/vim_dev/PFJkLtJu_nY/QU5aPeF5nsgJ why the cleaner solution would be that Vim sets this to the current window number from the outset.)

**Comment by majutsushi** [comment]
Yeah, that's what I was referring to above. But it would still be nice if it would work without that Vim change.

**Comment by Konfekt** [comment]
Well, before it worked in Vim but because two errors cancelled each other out. The alternate window was 0 after entering a new tab (but after closing the alternate window the current window number) but then again `0wincmd w` was valid. The latter error was fixed, the former not yet. I better stop here :)
