### ISSUE TITLE
tagbar-2.6.1 short help message contains hardcoded <F1> key

### ISSUE THREAD

**Issue by Coacher** [majutsushi/tagbar#245]
Hello.

Tagbar window features short help message aka `Press <F1> for help`. However, if `tagbar_map_help` is set to something else, then this message is misleading. Long help displays proper keybinding via `s:get_map_str('help')`. There should be no hardcoded value and proper keybinding should be worked out in the same way for the short help message as well.

Please fix.

**Comment by majutsushi** [comment]
Thanks, fixed.
