### ISSUE TITLE
Annotate C storage classes

### ISSUE THREAD

**Issue by Wyatts** [majutsushi/tagbar#250]
I'm dealing with legacy C: big files with lots of encapsulation via static functions, so tagbar has been invaluable.  But I noticed today it would be very useful to have an at-a-glance way to tell what symbols are static or extern.  I can hit space on each signature or highlight and wait a couple seconds, but when there are dozens of functions that's really tedious.  Something similar to how it handles C++ public and private would be enough to satisfy me: + for extern and - for static.  (Unrelated, but I wonder if there aren't better characters to indicate that stuff?)

**Comment by majutsushi** [comment]
I recently merged #238, which I think should do what you want as far as possible given the information that ctags provides. Note that for `extern` declarations to show up you have to add the `x` kind to your C Tagbar configuration.

**Comment by Wyatts** [comment]
Oh, excellent!  Guess I should update more often, haha.  Thanks.
