### ISSUE TITLE
Goto caret-position member definition?

### ISSUE THREAD

**Issue by vexe** [majutsushi/tagbar#251]
Hi there,

It seems that Tagbar can easily navigate to any member definition if I highlight one and press enter. Nice. However; is there anyway to do the same thing when I have my cursor over the member I'd like to find the definition for? Ex.

<code>
public class Test
{
    public int x;
    void Method()
    {
         // ....
         if (x| == value) ...
    }
}
</code>

| is where my cursor's at, then say I hit < leader >gd and then it takes me to "public int x;" just like pressing enter on 'x' in the tagbar.

Is that possible? If so, how?

Thanks!

**Comment by vexe** [comment]
I tried this simple idea

<code>
	nnoremap <leader>gd *<C-w>pn<cr>n:nohlsearch<cr>
</code>

so the idea is that if tagbar is open, I can hit star (*) on the current word under the cursor, go to Tagbar window (<C-w>p), go next (n) that will find what I searched for (which is whatever was under the cursor) then hit enter to get me to it in the file, then clear search highlight and enter. But it didn't work unfortunately, it manages to jump to tagbar finding the right member, but when it comes time to hit enter and goto it in the file, it doesn't do it. (I also noticed there's a small delay of when you hit enter in tagbar and when it takes you to the actual member)

**Comment by vexe** [comment]
Oh right... it's treating < cr > as if it was inserted in normal mode! which would go down to the next line. hmmm

**Comment by majutsushi** [comment]
Navigating to definitions like that is not really what Tagbar is for. This functionality is already built into Vim with its tag-navigating commands (see `:help tags-and-searches`). This requires creating a `tags` file, which [easytags](https://github.com/xolox/vim-easytags) can help you with.
