### ISSUE TITLE
Confusion with multiple scopes with the same name

### ISSUE THREAD

**Issue by luben** [majutsushi/tagbar#254]
Hello,

I am trying to improve the Scala integration in vim and I am currently focused on providing proper ctags support. It may be totally my fault, in this case any advise will be helpful.

So my ctags extractor produces these lines:
```
SQStreamSource	sqhttpd.scala	/^class SQStreamSource(query: String, config: Config) extends ActorPublisher[ByteString] with ActorLogging {$/;"	access:public	kind:c	package:streamquery
SQStreamSource	sqhttpd.scala	/^object SQStreamSource {$/;"	access:public	kind:o	package:streamquery
apply	sqhttpd.scala	/^  def apply(query: String)(implicit cfg: Config) = Source[ByteString](Props(classOf[SQStreamSource], query, cfg))$/;"	access:public	kind:m	object:streamquery.SQStreamSource
cfg	sqhttpd.scala	/^  def apply(query: String)(implicit cfg: Config) = Source[ByteString](Props(classOf[SQStreamSource], query, cfg))$/;"	access:public	implementation:implicit	kind:V	method:streamquery.SQStreamSource.apply
query	sqhttpd.scala	/^  def apply(query: String)(implicit cfg: Config) = Source[ByteString](Props(classOf[SQStreamSource], query, cfg))$/;"	access:public	kind:V	method:streamquery.SQStreamSource.apply
```

What it says is that I have a class (kind:c) SQStreamSource and an object of the same name(kind:o). Then the apply method is in the scope of the SQStreamSource object and has "query" parameter.

In the tagbar I get properly the apply method in the object scope:
```
 ▼ SQStreamSource : object
      <init> : method
      apply : method
```
but I why I don't get its parameters in it's scope?

Then the same "apply" method appears in the class scope:
```
  ▼ SQStreamSource : class
      [values]
      cfg
      ...
    ▶ <init> : method
    ▼ apply* : method
        [values]
        cfg
        query
    ▶ deliver : method
```
with all the params. Note there is an * after the method name. Does it means that the method was auto-created by tagbar?

My understanding is that when tagbar tries to add the params with scope "method:streamquery.SQStreamSource.apply" it auto-creates the method in the first scope that matches that path. Is there a way to hint tagbar (and all the other ctags bases utils) that the params is in the scope of the method apply of the object SQStreamSource not method apply of class SQStreamSource (that do not exists)?

Thanks in advance

**Comment by luben** [comment]
BTW, here is the tagbar config that I am using:
```
let g:tagbar_type_scala = {
    \ 'ctagstype' : 'scala',
    \ 'kinds'     : [
      \ 'p:packages',
      \ 'V:values',
      \ 'v:variables',
      \ 'T:types',
      \ 't:traits',
      \ 'o:objects',
      \ 'O:cobjects',
      \ 'c:classes',
      \ 'C:cclasses',
      \ 'm:methods:1'
    \ ],
    \ 'sro'        : '.',
    \ 'kind2scope' : {
        \ 'p' : 'package',
        \ 'T' : 'type',
        \ 't' : 'trait',
        \ 'o' : 'object',
        \ 'O' : 'case_object',
        \ 'c' : 'class',
        \ 'C' : 'case_class',
        \ 'm' : 'method'
    \ },
    \ 'scope2kind' : {
      \ 'package' : 'p',
      \ 'type' : 'T',
      \ 'trait' : 't',
      \ 'object' : 'o',
      \ 'case_object' : 'O',
      \ 'class' : 'c',
      \ 'case_class' : 'C',
      \ 'method' : 'm'
    \ }
\ }
```

**Comment by luben** [comment]
Actually I figured it out: tagbar does not understands "kind:f" syntax, it should be just "f"

**Comment by majutsushi** [comment]
Yes, that syntax was unsupported until now because no-one was using it. I have added support for it now, so your example should work.
