### ISSUE TITLE
Ctag doesn't work with Mac

### ISSUE THREAD

**Issue by xavierartot** [majutsushi/tagbar#256]
Hi,
I have this error:
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
GNU ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.
net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'ctags' --version"
Command output:
/Library/Developer/CommandLineTools/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...

I installed:
brew install ctags
the in my path:
/usr/bin/ctags

I tried too:
0 let g:tagbar_ctags_bin = '/usr/bin/ctags'

Still doesn't work?

Thank you

**Comment by xavierartot** [comment]
fixed:
https://thomashunter.name/blog/installing-vim-tagbar-with-macvim-in-os-x/

**Comment by majutsushi** [comment]
Glad you got it working. I'm not sure why it didn't work out of the box, maybe
there was an issue with the PATH setup. I hope you didn't install ctags
manually like in that article, just setting the g:tagbar_ctags_bin variable to
your brew-installed ctags should make it work.

**Comment by xavierartot** [comment]
I did ?
let g:tagbar_ctags_bin = '/usr/bin/ctags'
It didn't work :(

**Comment by majutsushi** [comment]
I don't think `/usr/bin/ctags` is the one that homebrew installed. Try running `brew --prefix` to see where homebrew installs its packages.

**Comment by xavierartot** [comment]
[local master] brew --prefix
/usr/local

let g:tagbar_ctags_bin='/usr/local/bin/ctags'  

I have the same link.

**Comment by majutsushi** [comment]
I'm not sure what you mean by "link" here; is it working with this setup? If
not then I'm afraid I don't know what else could be wrong, I've never used
homebrew myself. But if you have it working with a manual installation then
that's totally fine too of course.

**Comment by xavierartot** [comment]
It works fine, thank you for your work :)

**Comment by 20015jjw** [comment]
`brew install ctags` worked for me. Sierra, vim 8.0.

**Comment by longkai** [comment]
For some reason, e.g. you have Emacs.app installed, after `brew install ctags` you still need `brew link --overwrite ctags`.

Hope it helps.
