### ISSUE TITLE
Focus is on main window and not on Tagbar window

### ISSUE THREAD

**Issue by sivaswami** [majutsushi/tagbar#261]
I used F8 to activate tag bar. But focus is on main window and not on Tagbar window. How to switch focus to tag bar window and main window alternatively for effective code browsing. Right now I have to switch using ctrl w,w

**Comment by majutsushi** [comment]
I'm not entirely sure what you're asking for, but if you look at the documentation to `:TagbarOpen` there's probably a way to make it do what you want.

**Comment by sivaswami** [comment]
Hi I am using tagbartoggle

**Comment by majutsushi** [comment]
What you are using to open Tagbar is irrelevant, you can call TagbarOpen while
Tagbar is already open. Just have a look at the documentation that I mentioned.

**Comment by j5shi** [comment]
But with tagbar buffer open and not focused, call `TagbarOpen` won't gain focus to tagbar buffer, the focus remain where it was and that's the problem that sivaswami met.

**Comment by j5shi** [comment]
@sivaswami use `TagbarOpen -j`.

**Comment by majutsushi** [comment]
Almost, `TagbarOpen j` without the `-`.

**Comment by taurzk** [comment]
let g:tagbar_autofocus = 1

**Comment by taurzk** [comment]
let g:tagbar_autofocus = 1
