### ISSUE TITLE
PHP tagbar highlights variables

### ISSUE THREAD

**Issue by unphased** [majutsushi/tagbar#266]
Hi, I was wondering if there is a way configure the behavior of the tagbar highlight to only show me the name of the function that I am inside of, rather than have it point out which variables I am near? It would make the highlight much more generally useful.

**Comment by majutsushi** [comment]
Not directly, but you can show the name of the current function/method in the
statusline by using the tagbar#currenttag() function. Have a look at ":h
tagbar-statusline".

**Comment by alerque** [comment]
It seems like this may be answered. If there is still something you are looking for in this plugin let us know.
