### ISSUE TITLE
exuberant ctags not found

### ISSUE THREAD

**Issue by the-pw** [majutsushi/tagbar#267]
Tagbar: Exuberant ctags not found at '/home/user/ctags-5.8'!
Please check your g:tagbar_ctags_bin setting.

I have updated my bashrc with the following:

CTAGS=/home/user/ctags-5.8 
export CTAGS
PATH=$PATH:$CTAGS
export PATH

when I run ctags --version its still set to gnu, but I figured that tagbar would search the PATH rather than the default.

I have the following set in my vimrc:
let g:tagbar_ctags_bin="/home/user/ctags-5.8"

I got exuberant ctags version 5.8 from the link to sourceforge, and I extracted it to /home/user

Please advise.

**Comment by majutsushi** [comment]
Vim, and thereby Tagbar, inherits the PATH variable from the process that
started it. If you change PATH in your bashrc but then start GVim from a menu
it won't pick up that change.

Setting the g:tagbar_ctags_bin variable like you're doing will overwrite
whatever can be found in PATH, though. But unlike PATH it has to be set to the
actual executable, not the directory in which it is found. So you would have
to set it to something like this:

let g:tagbar_ctags_bin="/home/user/ctags-5.8/ctags"

**Comment by the-pw** [comment]
I see, makes sense.

However, I'm using the terminal version and launching it from the terminal. And In my ctags-5.8 directory there is no ctags file , there is ctags.1 ctags.h ctags.spec and ctags.html

I tried as you suggested but every time I tried :TagBar it told me to check again.

**Comment by majutsushi** [comment]
You seem to have downloaded the source archive instead of a compiled version. So you would have to compile it first to make it work. But the better alternative would probably be to install a package for your operating system. Since you seem to be using linux there should be a package called `exuberant-ctags` or `ctags-exuberant` in your package manager.

**Comment by the-pw** [comment]
That fixed it, I can be such a moron! Now to find out why my function key mappings are no longer working. Its unrelated to the ctags so I won't ask here! Thanks for your help.

**Comment by majutsushi** [comment]
Glad you got it working!
