### ISSUE TITLE
Tags have blank lines between them for JS files

### ISSUE THREAD

**Issue by chrisjohnson** [majutsushi/tagbar#269]
As the title says, my tags show up with a blank line between each one for JS files. Here's a screenshot: https://i.imgur.com/Hqqqva2.png

Here, a friend running tagbar on an older version is looking at the same file, and gets much different output (granted his .ctags has no entries for JS and merely uses defaults, though we both use the exact same ctags version): http://screencast.com/t/Ys5MfkPiS

Each of my tags is listed with a blank line between, which makes navigating tags a pain.

I'm using the latest HEAD on master, whereas he's using revision 399b75256ac7

I tried using his revision, but I get errors when I open tagbar on JS files (mentioned in the ticket I just closed).

My .ctags file: http://pastie.org/pastes/10187097/text

And here's the output I see when I use a blank .ctags: https://i.imgur.com/1zox4d0.png

**Comment by chrisjohnson** [comment]
Here's my tagbar when I'm looking at a PHP file: https://i.imgur.com/wgVQYMV.png

Notice no spaces between lines. The doubling of each entry is confusing (I'll submit an issue for that), but at least no space between lines

**Comment by majutsushi** [comment]
You can set the `g:tagbar_compact` variable to `1` to remove the blank lines, as explained in `:h tagbar-configuration`.
