### ISSUE TITLE
PHP tags are listed twice

### ISSUE THREAD

**Issue by chrisjohnson** [majutsushi/tagbar#270]
When I open my tagbar on a PHP file, the tags are listed twice. When I run ctags command line, I only see each item listed once, however when I view the tagbar... https://i.imgur.com/wgVQYMV.png

**Comment by majutsushi** [comment]
This seems to work fine for me, at least based on the information that Ctags
provides. Are you still seeing this? What does the output look like when you
run Ctags manually as described in ':h tagbar-issues'? Could you provide an
example file?

**Comment by chrisjohnson** [comment]
Can't share the file, it's employer's private code, but I can give you a screenshot of my tagbar with the doubled items: http://imgur.com/VPIAi.png

And the result of the ctags command: https://transfer.sh/XDlDO/ctags-output

**Comment by majutsushi** [comment]
Hmm, if I pass the ctags output you posted to Tagbar I get all the tags only
once, as it should be. Are you using the latest version? Could you please
create a logfile as described in ':h tagbar-issues'?

**Comment by alerque** [comment]
Please feel free to comment with information if this is still an issue for you @chrisjohnson, but I can't replicate it either and it's been a while without a log file. If there is an issue with the plugin we're happy to look into it, but I'm going to close the issue tracking it until we have confirmation that there even is an issue. Thanks for understanding.
