### ISSUE TITLE
TagbarToggle and then vim exit

### ISSUE THREAD

**Issue by nwf5d** [majutsushi/tagbar#272]
I use pathogen to manage vim plugins, and install tagbar. But when i tagbarToggle then vim exit.

**Comment by nwf5d** [comment]
VIM version:7.2  
ctags version:5.5.4

**Comment by mpetazzoni** [comment]
See #271, I'm having issues with TagBar making Vim quit unexpectedly when closing a buffer.

**Comment by majutsushi** [comment]
This is probably fixed after #234. Please reopen if you can still reproduce it.
