### ISSUE TITLE
How to override the "Exuberant ctags" validation checking?

### ISSUE THREAD

**Issue by meoow** [majutsushi/tagbar#276]
I am trying to use this [version](https://github.com/universal-ctags/ctags) of ctags which is
> This project continues the development of exuberant-ctags, but with the work hosted at github.

Due to the information of `--version` has been changed, which contains neither "Exuberant" nor version number, tagbar fails to recognize it as a exuberant-ctags.
Is there a way I can override or disable the ctags validation checking?

**Comment by majutsushi** [comment]
I just merged a pull request that should fix this issue.
