### ISSUE TITLE
Additional args for ctags

### ISSUE THREAD

**Issue by zakilo** [majutsushi/tagbar#277]
Is there a way to make Tagbar execute ctags with additional args ?
That is, I assume Tagbar execute 
`ctags myfile.cpp`, 
but now I want it execute 
`ctags -I_SOMETHING_TO_IGNORE myfile.cpp`. 
I have read the Tagbar document, but I can't find a solution.

**Comment by Shtucer** [comment]
From doc:
`let g:tagbar_ctags_bin = 'C:\Ctags5.8\ctags.exe'`

Did you try something like this?

`let g:tagbar_ctags_bin = 'C:\Ctags5.8\ctags.exe -I_SOMETHING_TO_IGNORE'`

**Comment by Shtucer** [comment]
In other hand:
`:he tagbar-extend` is the way to change type-related difintions.

**Comment by zakilo** [comment]
Yes, I tried `let g:tagbar_ctags_bin=/usr/bin/ctags -I_SOMETHING_TO_IGNORE`, but it failed with `Tagbar: Exuberant ctags not found at '/usr/bin/ctags -I__SOMETHING_TO_IGNORE`.

Here is the output of `ctags --version`:
`Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert`
`  Compiled: Oct  7 2014, 13:52:37`
`  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net`
`  Optional compiled features: +wildcards, +regex`

And the output of `ls -l /usr/bin/ctags`:
`lrwxrwxrwx. 1 root root     23 Mar 22  2014 /usr/bin/ctags -> /etc/alternatives/ctags*`

**Comment by zakilo** [comment]
After run `:TagbarGetTypeConfig cpp`, I add this code in .vimrc :
`let g:tagbar_type_cpp = {`
`    \ 'ctagsargs' : '-I_GLIBCXX_VISIBILITY+ -I_GLIBCXX_USE_NOEXCEPT',`
`    \ 'kinds' : [ `
`        \ 'd:macros:1:0',`
`        \ 'p:prototypes:1:0',`
`        \ 'g:enums',`
`        \ 'e:enumerators:0:0',`
`        \ 't:typedefs:0:0',`
`        \ 'n:namespaces',`
`        \ 'c:classes',`
`        \ 's:structs',`
`        \ 'u:unions',`
`        \ 'f:functions',`
`        \ 'm:members:0:0',`
`        \ 'v:variables:0:0',`
`    \ ],`
`\ }`

But Tagbar shows "No tags found". Am I doing wrong ?

**Comment by majutsushi** [comment]
The `ctagsargs` field is for ctags-compatible programs, not ctags itself, as it will replace the entire argument list with the ones you specify.

For your case there are two ways to achieve what you want:
- Put your `-I` definitions into your `~/.ctags` file. This way they will automatically be available for every ctags execution.
- If you don't want those definitions to be available globally you can put them into a separate file and use the `deffile` field of a type definition to point to it. That file will be passed to ctags using its `--options` argument so it has the same syntax as the `~/.ctags` file.

**Comment by zakilo** [comment]
Many thanks ! ! Problem solved !
