### ISSUE TITLE
Closing tagbar resizes splits

### ISSUE THREAD

**Issue by thirtythreeforty** [majutsushi/tagbar#282]
First, thanks for the awesome plugin.  It makes my life a bit easier.

I've noticed that when I close the tagbar, the splits that were present are moved around.  It seems that they are redistributed to be even splits across the terminal window.  This is of course rather unintuitive and a bit jarring, especially considering that the tagbar keeps splits exactly where they are when it opens.

To reproduce this, open vim, then:

```
:vsp
10 Ctrl-W <
:TagbarOpen
:TagbarClose
```

The split should move to its original position.

Is this a bug or expected behavior?  If it's the latter, how much trouble would it be to preserve split positions?

**Comment by cbates-** [comment]
Sounds like this issue: https://github.com/majutsushi/tagbar/issues/252

**Comment by thirtythreeforty** [comment]
Great, thanks for the pointer.
