### ISSUE TITLE
Hide the `blocks` section in Tagbar when editing CoffeeScript files

### ISSUE THREAD

**Issue by statico** [majutsushi/tagbar#285]
Tagbar is wonderful. However, when I'm browsing CoffeeScript I'll occasionally leave the cursor over an `if` statement:

![image](https://cloud.githubusercontent.com/assets/137158/8890504/1707da62-32b8-11e5-8a84-1c2cdbc64837.png)

And the Tagbar will jump to some giant section called `blocks`:

![image](https://cloud.githubusercontent.com/assets/137158/8890502/02faad92-32b8-11e5-9ab5-edf6e449e00a.png)

Is there a way I can hide the `blocks` section in Tagbar when editing CoffeeScript files?

**Comment by majutsushi** [comment]
Yes, you can. The best way to do this would be to go to your `~/.vimrc` and run the command `:TagbarGetTypeConfig <coffeescript filetype>`, which will paste the basics of the Tagbar configuration of that filetype at the current position. You can then simply remove the `blocks` entry from that list.
