### ISSUE TITLE
Manually update tags?

### ISSUE THREAD

**Issue by vexe** [majutsushi/tagbar#289]
Currently tagbar updates the tags automatically on save/buffer change etc. I save very often, and it slows vim down a lot (at least 2 seconds for a very trivial cpp file). I went over the help/docs and I didn't see any option that lets me do the update myself. I saw one deprecated option 'g:tagbar_updateonsave_maxlines' and it says that tagbar will now always update on save. I don't know the reasoning behind this. Why would you force it upon your users who don't want that behavior?

I want to manually update the tags myself (when I open/close tagbar), not on save or buffer change. Is there no way to do that?

**Comment by yqrashawn** [comment]
Require for functions to disable updating tag automatically.

**Comment by majutsushi** [comment]
The updating is now done on the first `CursorHold` event after writing a file, so it should be much less noticeable.

**Comment by j5shi** [comment]
And how to disable tag auto updating?

**Comment by gqqnbig** [comment]
Is it possible to force update even the buffer isn't changed? 

I'm writing universal ctags rules and want to debug the rules. Currently every time I changed the rule, I have to reopen my test file and load the tags.
