### ISSUE TITLE
cannot toggle Tagbar when using netrw

### ISSUE THREAD

**Issue by gavinchou** [majutsushi/tagbar#291]
when using netrw to browse a direcotry:

    vim /some/path/of/directory

or, in vim

    :e /some/path/of/directory

and then open a file and toggle tagbar with

    :Tagbar

then, tagbar wont work, tagbar flashes and quits
the problem occurs in the following function (autoload/tagbar.vim), 
` call s:goto_win(tagbarwinnr, 1)`

    " s:QuitIfOnlyWindow() {{{2
    function! s:QuitIfOnlyWindow() abort
        let tagbarwinnr = bufwinnr('__Tagbar__')
        if tagbarwinnr == -1
            return
        endif
    
        let curwinnr = winnr()
        let prevwinnr = winnr('#') == 0 ? curwinnr : winnr('#')
        call s:goto_win(tagbarwinnr, 1)

i (temporally) fix it by modifying this function,

    " s:QuitIfOnlyWindow() {{{2
    function! s:QuitIfOnlyWindow() abort
       if bufwinnr('__Tagbar__') == winnr() && tabpagewinnr(tabpagenr(), '$') == 1
            exe "q"
        endif
        return
    endfunc

 it seems i fixed, maybe there is a better way?

ps. it seems the logic of the original script is fine, but somehow it is not, lets fix it!

**Comment by symbolix** [comment]
I am also experiencing issues related to loading files through the `netrw`. Once I select the file to be loaded or switched to, I get the following error:

    Error detected while processing function <SNR>102_QuitIfOnlyWindow[28]..<SNR>102_goto_win:
    line    8:
    E16: Invalid range: 2wincmd w

Is it possible to fix this? I am using VIM 7.4.1553 with `netrw` v155. `netrw` is a core component of VIM. This plugin should be compatible with VIM's native file browser.

**Comment by qwIvan** [comment]
+1

**Comment by ggaaooppeenngg** [comment]
+1

**Comment by SoPudge** [comment]
i have the same problem

**Comment by majutsushi** [comment]
I think this should be fixed now. Sorry for the long delay.
If there's still a problem please reopen this issue.
