### ISSUE TITLE
Sort parameter of TagbarStatusFunc() with user-defined types

### ISSUE THREAD

**Issue by lifepillar** [majutsushi/tagbar#292]
When a user-defined type has an explicit `sort` keyword, e.g.:

```
let g:tagbar_type_markdown = { ... 'sort': 0, ... }
```

the `sort` parameter of `TagbarStatusFunc()` is not synchronized with the type's key, but (I think) it is always passed the value of `g:tagbar_sort`.

**Comment by majutsushi** [comment]
This should now finally be fixed, sorry for the long delay.
