### ISSUE TITLE
View C++ standard library source with tagbar?

### ISSUE THREAD

**Issue by kawing-chiu** [majutsushi/tagbar#293]
I'm reading the source of the C++ standard library (libstdc++). However, while tagbar works on normal C++ files, in these standard library sources it only shows:
```
functions
   _GLIBCXX_VISIBILITY(default)
```
How could I make tagbar work with standard library sources?

**Comment by kawing-chiu** [comment]
I've found a 'solution' that is not really a solution: use clang's standard library source (libcxx) instead of gcc's (libstdc++). The source of libcxx is much more friendly to ctags and tagbar.

**Comment by majutsushi** [comment]
Great that you found a workaround. This is most likely a Ctags issue and not a Tagbar issue. If you're still interested in solving this in a better way I would suggest checking out [Universal Ctags](https://ctags.io/) to see if this has been fixed there.

**Comment by kawing-chiu** [comment]
Yeah, Universal Ctags is great. I've already found out that, too :)
