### ISSUE TITLE
support configuration option to put the window at the left

### ISSUE THREAD

**Issue by nicolas33** [majutsushi/tagbar#295]
Could not find such feature. :-)

**Comment by Shtucer** [comment]
`Opening and closing the Tagbar window~
Use |:TagbarOpen| or |:TagbarToggle| to open the Tagbar window if it is
closed. By default the window is opened on the right side, set the option
|g:tagbar_left| to open it on the left instead. If the window is already open,
|:TagbarOpen| will jump to it and |:TagbarToggle| will close it again.
|:TagbarClose| will simply close the window if it is open.`

**Comment by nicolas33** [comment]
Great !!!! I should have read to doc more closely, sorry. :-)
