### ISSUE TITLE
support hide non public methods in python

### ISSUE THREAD

**Issue by nicolas33** [majutsushi/tagbar#296]
Conventional "private" methods starts with `_`.

**Comment by Shtucer** [comment]
I think it's issue related with `ctags`. You could set your own rule for python. See [examples](https://github.com/majutsushi/tagbar/wiki) for some languages. BTW ctags and TagBar supports built-in methods such as  `__str(self)__`.

**Comment by majutsushi** [comment]
Tagbar supports the `g:tagbar_hide_nonpublic` option to do this. If that doesn't do what you want in Python then I would recommend opening an issue with [Universal Ctags](https://github.com/universal-ctags/ctags).
