### ISSUE TITLE
Throws up constantly with 115_AutoUpdate

### ISSUE THREAD

**Issue by ain** [majutsushi/tagbar#297]
As also discussed on scrooloose/syntastic#1592 the plugin constantly throws up when opening a new Ruby file or saving it:

```
Error detected while processing function <SNR>115_AutoUpdate..<SNR>115_ProcessFile:
line   40:
E482: Can't create file /var/folders/6f/1zt06xc97cv5kbw8lr8grtr80000gp/T/vxHbEVi/16.rb
```

**Comment by majutsushi** [comment]
Hmm, I am unable to reproduce this issue with your configuration (under Linux), even if I set the option from the linked issue that enables autocommand nesting again. I see that you have removed Tagbar from your configuration for now, but if you're willing to give it a try again and you can still reproduce the problem then please reopen this issue and I'll try to dig into it (unfortunately I don't have a Mac around for testing).
