### ISSUE TITLE
Windows: tagbar won't detects ctags.

### ISSUE THREAD

**Issue by Shtucer** [majutsushi/tagbar#300]
I has `ctags` in the `%PATH%` but when I try `TagbarToggle` I have weird error message:

```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "ctags --version"
Command output:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul  9 2009, 17:05:35
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +win32, +regex, +internal-sort
Press ENTER or type command to continue
```

Sometimes `TagBar` says: `GNU ctags will NOT WORK....`
I've same result with `let g:tagbar_ctags_bin=full_path_to_ctags.exe`. How can I fix it?

**Comment by majutsushi** [comment]
Hey, sorry for not following up earlier. If you're still having this issue it would be great if you could try again with the latest version and create a debug log with it as described in `:h tagbar-issues`.

This may also be related to #352.

**Comment by alerque** [comment]
I'm going to close this issue because (given that Windows support generally works) this has either long since been fixed or was a user setup error. In the event there is still something that needs fixing please feel free to post more details on this issue and we'll have another look.
