### ISSUE TITLE
Tagbar crashes when I hover mouse over a function

### ISSUE THREAD

**Issue by lionelmessi** [majutsushi/tagbar#301]
Platform: Windows

I am using tagbar with exuberant ctags and when I hover my mouse over a tag, it shows the details in a white popup but soon after GVIM crashes.

Anyone able to see this?

**Comment by lionelmessi** [comment]
Here is the msg, I got from MSVC

The thread 0x1564 has exited with code 0 (0x0).
Unhandled exception at 0x73B8BD26 (comctl32.dll) in gvim.exe: 0xC0000005: Access violation reading location 0x00000004.

**Comment by majutsushi** [comment]
That's quite odd, but not really a Tagbar issue. It may be a problem with the `balloonexpr` functionality under Windows. If you're still having this problem then I would recommend opening an issue in https://github.com/vim/vim.
