### ISSUE TITLE
Any steps missing from Wiki jsctags instructions?

### ISSUE THREAD

**Issue by jonahx** [majutsushi/tagbar#303]
I've installed tern_for_vim and jsctags as a devDependency on my project, but I still see no new ctags file and no new tags in tagbar.

I'm sure I've missed some simple step needed to cause the generation of the ctags, but I can't figure out what it is.... Hoping you can help.  Thanks.

## UPDATE
I figured this out.  I just had to install jsctags globally vs only in my project, and then tagbar picked it up and started working automatically.

**Comment by TwoD** [comment]
I that all you did? I still get no tags.
