### ISSUE TITLE
Error when quit file while tagbar open

### ISSUE THREAD

**Issue by codinfox** [majutsushi/tagbar#305]
I got the following error when I try to close file while tagbar is still open:

![screen shot 2016-02-04 at 7 46 38 pm](https://cloud.githubusercontent.com/assets/2647449/12834801/7450e548-cb78-11e5-962d-409d15d1318b.png)

I am using tagbar with macvim.

**Comment by joegrasse** [comment]
I also am getting this error. Using tagbar with linux console vim.

**Comment by joegrasse** [comment]
@codinfox if you don't mind, check if my pull request fixes your issue.

**Comment by ahamidi** [comment]
I'm experiencing the same issue.

Any clue as to a potential fix/workaround?

**Comment by joegrasse** [comment]
@ahamidi did you try my pull request? Interested to see if it works or if you have the same issue as @codinfox.

**Comment by majutsushi** [comment]
The pull request is now merged.
