### ISSUE TITLE
Support for all open buffers

### ISSUE THREAD

**Issue by lyager** [majutsushi/tagbar#309]
Tagbar is great. I do wish though it could work for all buffers currently open i Vim - thus showing all classes and navigate across buffers.. Is this feature already there or planned?

Br.

**Comment by majutsushi** [comment]
This is a bit out of scope. Tagbar is meant to show the outline of the current file just like an IDE would. Giving an overview of a whole project would be better suited for a separate plugin, especially since there would be several complications that would need to be handled to do it properly.
