### ISSUE TITLE
Is it right that Chinese characters or CJK characters cannot be recognized?

### ISSUE THREAD

**Issue by eduOS** [majutsushi/tagbar#312]
Hello,

I encounter a problem while editing a .tex file:

![5vb okq _v 9q zge7clf](https://cloud.githubusercontent.com/assets/8926535/13566850/9d29cdc6-e492-11e5-84b6-eb2721dfd81d.png)

If I want tagbar to show those CJK characters what should I do?

Best,
Lerner

**Comment by majutsushi** [comment]
This is a bug in Ctags unfortunately. I would recommend opening an issue in the [Universal Ctags](https://ctags.io/) project since it doesn't seem to have been fixed there yet either.
