### ISSUE TITLE
Universal Ctags doesn't generate tags for html

### ISSUE THREAD

**Issue by yashsriv** [majutsushi/tagbar#317]
Universal Ctags and Exuberant ctags does not generate tags for html yet the help file says that tagbar supports html. My tagbar only shows `No tags found`. Is there some way I can activate support for html files.

**Comment by pk-88** [comment]
I wasn't able to get the 'supported' HTML ctags to work in tagbar (using universal ctags), but I did get it to show class and id values by adding the following regex lines to .ctags:

`--regex-html=/id=\"([a-zA-Z0-9-]+)\"/\1/i,identifiers/`
`--regex-html=/class=\"([a-zA-Z0-9-]+)\"/\1/c,classes/`

then add this to .vimrc:

`let g:tagbar_type_html = {`
`\   'ctagstype' : 'html',`
`\   'kinds' : [`
`\	'i:identifiers',`
`\	'c:classes',`
`\   ],`
`\ }`

**Comment by majutsushi** [comment]
I've updated the support for the current version of Universal Ctags. Any other improvements would have to be made there first before they can be used in Tagbar.

**Comment by BonarBeavis** [comment]
HI,

uctags does now [generate](http://docs.ctags.io/en/latest/parser-html.html#html) tags for html, but tagbar still shows 'No tags found'.

**Comment by nerdfiles** [comment]
I'm also experiencing this issue. Anyone got any tips on the cause(s)? I'm getting tags for all other languages (JS, TypeScript, Python, CSS, markdown, etc).
