### ISSUE TITLE
Tagbar gets confused when class/struct declaration and definition is in the same file

### ISSUE THREAD

**Issue by moshev** [majutsushi/tagbar#321]
Test setup:

    void bar();
    
    struct A {
        int m;
    	void foo();
    };
    
    void A::foo() {
    }
    
    void bar() {
    }

If you put these lines in a file ending with .h, I get a `class A*` and a `struct A` in the tagbar window. If I change the struct to a class, I get proper grouping. That I can live with, but if I put them in a file ending with .cpp, I only get the `class A*` and no `struct A`, i.e. I'm missing the members. Even worse, if I inline the class definition, I get nothing!

**Comment by moshev** [comment]
On second thought, this appears to be a bug in universal-ctags, sorry.

**Comment by moshev** [comment]
Okay, so not a bug in universal-ctags: [issue ##984](https://github.com/universal-ctags/ctags/issues/984#issuecomment-225211124) Could you consider adding `--extra=+F` in the options passed to ctags?

**Comment by majutsushi** [comment]
This should be fixed in #314.
