### ISSUE TITLE
the tagbar is closing the gvim by the commad ":bd"

### ISSUE THREAD

**Issue by bigov** [majutsushi/tagbar#322]
Hi! I'm use gvim for C++ development. I found one problem: when deleting one of the buffers by command ":bd", the opened tagbar is closing gvim session with the main window and all other multiple early opened buffers. If you need, in the archive my complete vim's config. My Vim version is 7.4 (1829).

[vimfiles.zip](https://github.com/majutsushi/tagbar/files/331344/vimfiles.zip)

**Comment by majutsushi** [comment]
As mentioned in #234 this should finally be fixed now.
