### ISSUE TITLE
incorrect parse for references of array in c++

### ISSUE THREAD

**Issue by JianCheng** [majutsushi/tagbar#324]
Here is a demo to show the incorrect parse for references of array, where `FuncArray` is not detected as a function. 

```c++

template <class T, size_t N1, size_t N2>
inline bool 
FuncArray (const T (&a1)[N1], const T (&a2)[N2] )
{
}

int main (int argc, char const* argv[])
{
  return 0;
}
```

Any suggestion to solve this issue? Thanks.

**Comment by majutsushi** [comment]
This is an issue with Exuberant Ctags. It looks like it has been fixed in [Universal Ctags](https://ctags.io/), so I would recommend switching to that instead. If I use Universal Ctags it shows up correctly for me in Tagbar.
