### ISSUE TITLE
Is it possible to move the cursor to the tag name instead of beginning of line ?

### ISSUE THREAD

**Issue by wandersoncferreira** [majutsushi/tagbar#326]
Hi, 
I am amazed by this plugin. However, most of the time I have imports in my file and I see them in the tagBar just fine.

When I hit enter, it takes me to the beginning of the line where the import was done. I would like to open that imports using Ctrl+] from the current window not in the tagbar window. 

It would be enough if when I hit <cr> at the tag name inside the tagbar window and the cursor were automatically moved above to the tag name in my file (and them I hit ctrl + ]).

Is it possible? Do you have a better alternative?
Many thanks!!!

**Comment by majutsushi** [comment]
I've committed a change that tries to jump to the correct column by searching for the tag in the correct line if ctags doesn't already provide that information.

**Comment by wandersoncferreira** [comment]
nicely done! thanks
