### ISSUE TITLE
"No tags found"(ES6 project) in vim

### ISSUE THREAD

**Issue by lxynox** [majutsushi/tagbar#327]
I've successfully installed **Tagbar** and its dependency **Exuberant-ctag**(version5.8), it does work for VanillaJS, but i'm currently having some problem with **ES6** syntax support.

![screen shot 2016-08-18 at 11 38 51 pm](https://cloud.githubusercontent.com/assets/10333817/17798303/1553423c-659e-11e6-96f8-0f38778a6f7e.png)

From the pic above, it's obvious that my tagbar has some problem with interpreting ES6 syntax.  I already installed `tern_for_vim` and set up the `.tern-project` at the root level of repo. I know it works well with ES6, but i  cannot think of any solution to my current condition, do i need to generate any js tag files, can anyone give me any hints?

**Comment by lxynox** [comment]
Update: looks like it's caused by tern_for_vim doesn't work properly, will confirm to close this issue.

**Comment by jackson-dean** [comment]
@lxynox did you get this working. How did you do it?

**Comment by RainyLi** [comment]
This happens to me as well. Can anyone show us how to fix it?

**Comment by atoder** [comment]
I am also having this issue. Anyone solved this?
