### ISSUE TITLE
Incorrect file name in status bar in tagbar window

### ISSUE THREAD

**Issue by jpmv27** [majutsushi/tagbar#330]
When I first toggle tagbar on, the file name in the status bar of the tagbar window matches the name of the file from which I opened tagbar

If I then open a new file in the main window, the tagbar information is updated but the file name in the status bar isn't. This can be confusing, especially if TagbarTogglePause

**Comment by jpmv27** [comment]
Same issue happens when using :TagbarTogglePause.
If I pause, change file, then un-pause, the tagbar contents are updated to match the new file but the status line still shows the previous file

Should AutoUpdate() call SetStatusLine()? Or should callers of AutoUpdate() also call SetStatusLine() when appropriate?

**Comment by majutsushi** [comment]
This should be fixed now, thanks for the report!

**Comment by jpmv27** [comment]
I'm not sure the fix addresses the whole of the problem. I was also seeing the same issue when tagbar is open and I start editing a new file: the tagbar contents are updated but the filename in the status bar is not. Is that fixed too?

MV
P.S. My own proposed fix is in PR#335

**Comment by majutsushi** [comment]
Hmm, that seems to be working fine for me. Is it not working for you?

I did see your pull request, thanks for that! And also for noticing that the argument was redundant. As far as I can see both of the changes related to this issue are explicitly updating the statusline after a call to `AutoUpdate`, so calling it at the end of every `AutoUpdate` should cover both of those cases. Your changes would certainly be more efficient than calling it after every update, however the statusline can contain more information than just the file name and may thus need to update more often, and it shouldn't be an expensive call anyway. If it becomes a performance issue it could be changed later. Is that okay with you?

**Comment by jpmv27** [comment]
Never mind, I misread your commit.

Thanks
MV
