### ISSUE TITLE
Airline + Tagbar causing Key not present in Dictionary: bufnr

### ISSUE THREAD

**Issue by ffhaddad** [majutsushi/tagbar#337]
I'm not sure exactly what the problem is, but the combination of plugins Airline and Tagbar is causing the following error,

> Error detected while processing function <SNR>92_SetStatusLine[29]..airline#extensions#tagbar#get_status[5]..366:
> line   16:
> E716: Key not present in Dictionary: bufnr
> E15: Invalid expression: 'airline_c'. self._context.bufnr

The culprit seems to be line `999` in the file `tagbar/autoload/tagbar.vim`

`autocmd WinLeave   __Tagbar__ call s:SetStatusLine('noncurrent')`

I commented out this line and the error went away. I don't notice any broken or missing functionality either, so I'm not sure what this line does. Anything I can do to help debug this, please let me know.

Vim version: 7.4.2045
Tagbar: cloned today
Airline: cloned today from <https://github.com/vim-airline/vim-airline>

NOTE: If I disable Airline, this line does not cause any problems.

**Comment by majutsushi** [comment]
Sounds like it was this bug: https://github.com/vim-airline/vim-airline/issues/1251

**Comment by ffhaddad** [comment]
Resolved! :)
