### ISSUE TITLE
Opening new tab from tagbar buffer fails

### ISSUE THREAD

**Issue by jpmv27** [majutsushi/tagbar#345]
With g:tagbar_autofocus=1

1) vim
2) :e FILE
3) :ToggleTagbar
4) Leave focus in tagbar
5) :tabe (to open empty tab)

Expected result: a second tab is open and no tagbar is displayed
Actual result: Only one tab, showing empty buffer; tagbar still open displaying information for FILE

If at (5) we do ':tabe FILE2', then FILE2 buffer is opened in the first tab, replacing FILE, and the information in the tagbar is updated for FILE2

PR#343 does NOT fix this issue

**Comment by jpmv27** [comment]
Added some debug logging and extracted the following in both failing cases mentioned above.

2016-09-27 19:32:01.660694: QuitIfOnlyWindow tabpagenr=2 tagbarwinnr=1
2016-09-27 19:32:01.660855: QuitIfOnlyWindow tabpagenr=2 curwinnr=1 prevwinnr=1
2016-09-27 19:32:01.660974: goto_win(): 1wincmd w, 1
2016-09-27 19:32:01.661106: nextNormalWindow: tabpagenr=2
2016-09-27 19:32:01.661214: NextNormalWindow: buf=2 bufname=__Tagbar__
2016-09-27 19:32:01.661316: NextNormalWindow: skip unlisted
2016-09-27 19:32:01.661461: NextNormalWindow: return -1
2016-09-27 19:32:01.661600: QuitIfOnlyWindow... close tabpagenr=2

I have come across something similar while debugging another plug-in: when ":tabe" is done and the new tab is created and the first window is opened, we are still in the buffer from which ':tabe' was done. Then vim opens the new buffer in the window.

So, when the new tab+window are created, there is only one buffer in that tab, the __Tagbar__ buffer, so QuitIfOnlyWindow closes it.

**Comment by jpmv27** [comment]
A possible solution is to create a tab-scope variable when updating the tagbar buffer.

In the failing scenario above, QuitIfOnlyWindow could test for the existence of this tab-scope buffer. Since it does not exist, QuitIfOnlyWindow would not close the window.

In the alternate scenario (a tab with file window/buffer + tagbar window/buffer,) QuitIfOnlyWindow would apply the same test and, detecting the existence of the variable, proceed to close the window.

**Comment by majutsushi** [comment]
Okay, I think I've finally found a way to properly handle the case where a file window gets closed due to a `:quit` or `:bdelete`/`:bwipeout`. This should also fix the case you're mentioning here. Let me know if it doesn't work for you!

**Comment by majutsushi** [comment]
I've reused the `QuitPre` bit of your pull request #343, thanks for that idea! I must have missed that autocommand last time I looked at solving this issue.

**Comment by jpmv27** [comment]
Looks good!
MV
