### ISSUE TITLE
Tagbar does not update its window with vim 8

### ISSUE THREAD

**Issue by gnujeremie** [majutsushi/tagbar#346]
I recently upgraded to vim 8, and now it seems like the tagbar windows does not update its view after the first time it is opened (meaning, if I open tagbar from a new file, it keeps displaying the tags from the first file used to open it).

**Comment by majutsushi** [comment]
Can you still reproduce your issue even with my latest change?

**Comment by gnujeremie** [comment]
No it's ok, it seems to be fixed. Thanks a lot 👍
