### ISSUE TITLE
Updating to 2016.10.16 version causes the left-side tagbar working wrong

### ISSUE THREAD

**Issue by mhf-air** [majutsushi/tagbar#351]
I'm using vim8.0, and this is my tagbar config:
let g:tagbar_left=1                                                                                                                                                                            
let g:tagbar_width=50
let g:tagbar_iconchars=['▸', '▾']
au FileType go nested :TagbarOpen

After updated my tagbar to 2016.10.16 version, I found that all the stuff in the tarbar are the same color, and it automatically got the focus when I started vim. When I put the tagbar in the right side, it somehow works. I don't know why.

**Comment by majutsushi** [comment]
I just pushed a change that should make the cursor stay in the correct window
again. I can't reproduce your other issue though, are you still experiencing
this? If yes could you please generate a logfile as explained in
':h tagbar-issues' and make the file available somewhere? Thanks!

**Comment by mhf-air** [comment]
Thanks very much, all problems are solved!

Just a tiny thing, this is my config:
    au BufEnter * setlocal cursorline                                                                                                                                                              
    au BufLeave * setlocal nocursorline
    au BufEnter * setlocal cursorcolumn
    au BufLeave * setlocal nocursorcolumn
In previous versions, there are no cursorline and curnsorcolumn on the tagbar window in previous versions, but now there are. It's not a big problem, hopefully you can provide some tips for dealing with it.

**Comment by majutsushi** [comment]
I would recommend adding something like this to your vimrc:

au FileType tagbar setlocal nocursorline nocursorcolumn

I you never want to show the lines in Tagbar, even if you enter its window,
you should exclude Tagbar by having your autocommands do something like
"if &ft != 'tagbar' | setlocal foo | endif".

By the way, cursorline and cursorcolumn are window-local options, not
buffer-local ones, so you should probably use the 'WinEnter' and 'WinLeave'
autocommands instead of 'BufEnter/Leave'.

**Comment by mhf-air** [comment]
Thank you very much! Your answer also solves a similar problem I'm having with cursorline in Nerdtree. Now my config becomes:
    au BufEnter * setlocal cursorline cursorcolumn
    au WinLeave * setlocal nocursorline nocursorcolumn
    au FileType tagbar setlocal nocursorline nocursorcolumn
