### ISSUE TITLE
How to ask tagbar to show class prototype?

### ISSUE THREAD

**Issue by kawing-chiu** [majutsushi/tagbar#354]
I'm using tagbar with universal-ctags. When editing python files, currently the class entry is like this:
```
▼+GraphArray : class
```
I want tagbar to show the full prototype (include inheritance information) like this:
```
▼+GraphArray(_GraphBase): class
```
How can I do this? The prototype info is already there since when I press SPACE I can see it in the statusline. Just can't find a way to display it in tagbar.

**Comment by majutsushi** [comment]
The info is already "there" only in the sense that the SPACE functionality
shows the line that the tag is defined in. Unfortunately there is no good way
to extract specific information from it, in this case the signature; at least
not in the general case. Extracting (parsing) that information is Ctags's job.

I would recommend opening an issue with Universal Ctags to provide the
signature for constructors in an extension field, once that is there it would
be easy to add support for it to Tagbar.
