### ISSUE TITLE
tagbar causes audible bell when installed via Vundle

### ISSUE THREAD

**Issue by cleary3** [majutsushi/tagbar#355]
I've observed that, when _tagbar_ is installed via the Vundle plugin manager, an audible bell is emitted whenever the _tagbar_ is initially toggled on. Subsequent toggles of _tagbar_ within the vim instance don't emit audible bells. But, once I quit the vim instance, open up vim again, and toggle the _tagbar_, the audible bell again occurs on that first toggle.

I've worked around the issue by not installing _tagbar_ via Vundle. I've found that the audible bell doesn't occur when installing _tagbar_ directly into my `.vim` directory or via another vim plugin manager, such as Pathogen. I've chosen the Pathogen route for now.

I'm using VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 30 2014 10:56:39). This is the default vim included with RHEL 7.

**Comment by majutsushi** [comment]
Should be fixed now.
