### ISSUE TITLE
ERROR after I update the latest plugin

### ISSUE THREAD

**Issue by ZEROCHAU** [majutsushi/tagbar#357]
After I update this version's tagbar, I can open it， but every time, it show me this error messages:
Error detected while processing function tagbar#ToggleWindow..<SNR>142_ToggleWindow..<SNR>142_OpenWindow:
line   94:
E121: Undefined variable: pprevwinnr
E15: Invalid expression: winnr() == pprevwinnr || winnr() == prevwinnr
My vim version is 7.4, on Centos 7, How can I fix it?

**Comment by majutsushi** [comment]
Should be fixed now.
