### ISSUE TITLE
'override' label instead of function name

### ISSUE THREAD

**Issue by darianndd** [majutsushi/tagbar#361]
Hi,

I am using Tagbar for a year and I must admit that it is "must have" tool when working with C++ code.
However, I noticed that it does not show function name when it has 'override' label (see screenshot of test.hpp file below). Could you take a look and tell me if I can change this behavior with some configuration setting (tagbar or vim) or it is an issue with tagbar?

![func_override_screenshot](https://cloud.githubusercontent.com/assets/23472395/20298603/1b5df1ae-ab17-11e6-975b-812048309e04.jpg)

I have  tested this on Tagbar from master branch (HEAD of my local repo below) and vim 7.4 (Ubuntu 14.04.5 LTS) :
`* 01f57ac - (HEAD, origin/master, origin/HEAD, master) Disable autocommands when deleting Tagbar buffer in HandleOnlyWindow (Mon, 7 Nov 2016 12:45:17 +1300) <Jan Larres>`

Thanks,
Darek

**Comment by majutsushi** [comment]
This is an issue with Exuberant Ctags. It has been fixed in [Universal Ctags](https://ctags.io), so I would recommend switching to that.

**Comment by darianndd** [comment]
Ok, I will try that. Thanks for help.

**Comment by darianndd** [comment]
Indeed, it works far better than exuberant-ctags. Again, thanks for help, because I did not aware of Universal Ctags.
