### ISSUE TITLE
how to close the fold automatically whenever I open vim?

### ISSUE THREAD

**Issue by keifkeifki** [majutsushi/tagbar#369]
I want to silence default behaviour， it make my editing laggy, thx

**Comment by majutsushi** [comment]
I don't quite understand what you mean. What fold(s)? In the Tagbar window, or the file window? Folds in the Tagbar window should have no effect on editing a file, and Tagbar is not responsible for folds in the file window.

**Comment by keifkeifki** [comment]
yes, the Tagbar window, I mean that all variables and functions will not be expand when i execute `:TagbarToggle`

**Comment by gasparch** [comment]
@keifkeifki you may redefine your language definition and put there which sections you want to be open by default.

See this line in my config - https://github.com/gasparch/vim-ide-elixir/blob/development/plugin/vim-ide-elixir.vim#L92

**Comment by majutsushi** [comment]
You can also configure the initial global foldlevel, see `:h g:tagbar_foldlevel`.
