### ISSUE TITLE
tagbar#currenttag('%s', '', 'f') contains unwanted apostrophes

### ISSUE THREAD

**Issue by kiryph** [majutsushi/tagbar#370]
Consider following tex file:
```tex
\documentclass[]{article}

\begin{document}
\section{Section}
\subsection{Subsection}
hello
\end{document}
```
While the cursor is on `hello`, running manually `:echo tagbar#currenttag('%s', '', 'f') ` returns `Section""Subsection`. They should be separated by a space or separating symbol.
I have installed the head version of universal-ctags:
```
❯ ctags --version
Universal Ctags 0.0.0(1f7ef34), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec  1 2016, 14:27:39
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc, +xpath
```

**Comment by majutsushi** [comment]
These two quotes (not apostrophes) are what is used by ctags as the "scope resolution operator" for LaTeX, similar to `.` for languages like Java. LaTeX does not have such an operator by itself, so ctags invents one to be able to represents scope hierarchies. For your case I would recommend simply passing the output of `currenttag()` through a `substitute()` call to replace it with whatever you want.

**Comment by kiryph** [comment]
Thanks for your help. I didn't expect that this is the reason. One can find the definition in the code of universal-ctags here: https://github.com/universal-ctags/ctags/blob/1da6e7e/parsers/tex.c#L200-L223.

(PS. also thanks for the reminder about apostrophes vs quotes 😄 )
