### ISSUE TITLE
syntax coloring is not enabled with vim 7.4.576

### ISSUE THREAD

**Issue by ravi2k16** [majutsushi/tagbar#373]
hi,
i am using vim 7.4.576 in debian 8.1 however syntax color is not enabled in tagbar window. my syntax color
option is on and in main window color is seen.

thanks....

**Comment by majutsushi** [comment]
Do you use any autocommands or similar to open Tagbar? If yes you may have to use the `nested` argument to them. Otherwise this should just work.

**Comment by ravi2k16** [comment]
Do you use any autocommands or similar to open Tagbar?
>>>> yes I also use taglist.vim

If yes you may have to use the nested argument to them.
>>>>  I could not understand this part. can you please elaborate more ?






thanks.

**Comment by majutsushi** [comment]
Sorry, I don't understand what taglist has to do with my question about
autocommands. What I meant was, do you use anything like what is described in
":h tagbar-autoopen" to open Tagbar? The use of the "nested" argument is also
demonstrated there.

**Comment by alerque** [comment]
@ravi2k16 Please feel free to comment if this is still an issue for you. If so please include some details about for vim rc setup so we can replicate it. In the meantime until there is more information I'm closing this issue because there isn't anything really actionable until we know more.
