### ISSUE TITLE
how to adjust width of tagbar window and other features

### ISSUE THREAD

**Issue by ravi2k16** [majutsushi/tagbar#374]
hi,
1. how can i increase/decrease width of tagbar window ?
2. how can i open tagbar window on left side of screen? currently it is opened on right by default.
3. how can i set the default setting of 'Toggle sort' to off ? currently it is on by default.

thanks,
ravi

**Comment by majutsushi** [comment]
This is all explained in the manual:

1. `:h g:tagbar_width`
2. `:h g:tagbar_left`
3. `:h g:tagbar_sort`
