### ISSUE TITLE
Tagbar doesn't display the C++14 example from Universal Ctags properly

### ISSUE THREAD

**Issue by Ferenc-** [majutsushi/tagbar#375]
I have the latest Universal Ctags (5f77993) and the latest tagbar (01f57ac).
When I try a [C++14 example from Universal Ctags](https://github.com/universal-ctags/ctags/blob/83dbec5554fa48bbde98c182f38d7ee3f89edc9d/Units/parser-cxx.r/cxx14-combined.d/input.cpp)  the tagbar output is completely wrong:

![image](https://cloud.githubusercontent.com/assets/6553695/20969315/bf5ffa54-bc88-11e6-9755-d13e4171c12c.png)

**Comment by majutsushi** [comment]
Are you sure you're actually using the latest Universal Ctags with Tagbar? I just tried it myself and it works fine for me.

**Comment by Ferenc-** [comment]
I am afraid I do:

`ctags --version

Universal Ctags 0.0.0(5f77993), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec  7 2016, 13:43:53
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc, +xpath
efergcz@elxa7qgwj12:~/ctags/bin$ `

And I couldn't find any other ctags installation on my system 

`lsb_release -a                               
                                                                                                                     
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty`

It happens in vim and neovim too:

`vim --version

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 18 2016 09:26:12)
Included patches: 1-92
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm -ldl `

`NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedanti
c -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git2016112
92243+2925+22~ubuntu14.04.1/build/config -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git201611292243+2925+22~ubuntu14.04.1/src -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git201611292243+2925+22~ubuntu14.04.1/.deps/usr/incl
ude -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git201611292243+2925+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git201611292243+2925+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-g2u
IRt/neovim-0.1.5ubuntu1+git201611292243+2925+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git201611292243+2925+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1
+git201611292243+2925+22~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git201611292243+2925+22~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-g2uIRt/neovim-0.1.5ubuntu1+git20
1611292243+2925+22~ubuntu14.04.1/build/include
Compiled by root@lgw01-27
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"`

Later I will also try on a different system.

**Comment by Ferenc-** [comment]
OK I tried on `openSUSE Tumbleweed`, with NVIM 0.1.7 and `VIM - Vi IMproved 8.0 (2016 Sep 12)` it didn't work on any of those either.
What is your configuration in which it works for you?
Do you have a Dockerfile perhaps?

**Comment by majutsushi** [comment]
I don't have any special configuration, and I just tried it again and it worked fine. I still think that the most likely explanation is that Tagbar is picking up an incorrect ctags executable somewhere. Could you please update Tagbar to the latest version and then create a logfile as explained in `:h tagbar-issues`? 

And could you also please post the output of the following command?
```
/path/to/uctags -f - --format=2 --excmd=pattern --extra= --fields=nksaSmt --file-scope=yes Units/parser-cxx.r/cxx14-combined.d/input.cpp
```

**Comment by Ferenc-** [comment]
Results from Ubuntu Trusty:
My universal ctags output seems okayish:
[output.txt](https://github.com/majutsushi/tagbar/files/659043/output.txt)

But my tagbar debuglog is very odd:
[tagbardebug.log.txt](https://github.com/majutsushi/tagbar/files/659046/tagbardebug.log.txt)

I did update tagbar and now I am on 1374077676238727a526d74824793a36ef2c0b73 but, I don't find the "Command output" or the "Exit code" anywhere.
Plus it's quite a mystery to me, why the date of the log equals to the Unix epoch, despite the fact that the system clock is properly set.

**Comment by majutsushi** [comment]
I'm not sure either why the timestamps are incorrect. I've seen that a few times but haven't been able to reproduce it. It's not really important, but if you're curious you can have a look at the two `gettime()` functions in `autoload/tagbar.vim` to see if you can make it work.

As for the log file, you're right that it's missing the actually interesting parts. Are you sure you've created it exactly as described in the help file? The `:TagbarDebug` command has to be called before any file processing has taken place. Do you maybe use the `currenttag()` function in your statusline? In that case you would have to comment it out temporarily before creating a log file so it doesn't get called before the debug command.

**Comment by Ferenc-** [comment]
Thank you! With your help I found out that there were indeed older versions of ctags hiding on my systems, and now I managed to hunt them down.
I really appreciate the assistance. Keep up the great work!
