### ISSUE TITLE
Something wrong when vim starts up with arguments

### ISSUE THREAD

**Issue by leiless** [majutsushi/tagbar#377]
I added the following two lines into my ~/.vimrc:
```
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() != 0 && !exists("s:std_in") | TagbarToggle | endif
```

It toggle(show) tagbar when vim starts up with arguments, but the error occurred:

> Error detected while processing VimEnter Auto commands for "*":
> E488: Trailing characters:  TagbarToggle | endif
> Press ENTER or type command to continue

(I'm sure the ~/.vimrc is UNIX text file)

**Comment by majutsushi** [comment]
This is due to how Vim parses autocommand lines. The easiest solution is to do one of these:
```
autocmd VimEnter * if argc() != 0 && !exists("s:std_in") | execute 'TagbarToggle' | endif
autocmd VimEnter * if argc() != 0 && !exists("s:std_in") | call tagbar#ToggleWindow() | endif
```
