### ISSUE TITLE
Too bright colors for access modifiers

### ISSUE THREAD

**Issue by manasthakur** [majutsushi/tagbar#378]
Hi @majutsushi ,

As the colors for access (and visibility) modifiers have been hardcoded (Green, Blue, Red), they look too bright (with high contrast) in 24-bit light colorscheme environments. Can you please link them to some existing elements that would change based on the colorscheme?

**Comment by majutsushi** [comment]
I don't think linking them to existing elements makes much sense. There are no existing elements that are logically similar, so the colours would essentially be random. But you can customise the colours as explained in `:h tagbar-highlight`.
