### ISSUE TITLE
Improvement: allow transforming taglist for full customization

### ISSUE THREAD

**Issue by gasparch** [majutsushi/tagbar#380]
Goal of this patch is to allow vimscript transformation of taglist loaded from external ctags program.
For Elixir/Erlang ctags generates not quite useful info. 

You can see on image - left is default ctags installation, right - with filter (removed duplicate names handle_* && init, because they are already in OTP section) and also added arity information. Also if you have function with 5 clauses - it will generate 5 entries in tagbar with some name (like handle_call did) without any additional useful information.

![tagbar-filter](https://cloud.githubusercontent.com/assets/942380/21074768/77afb25a-bf1a-11e6-892d-0ed5963f6dee.png)

So use may include:
- removing some redundant/extra tags which are not possible to remove with ctags (because it uses very simple regexp engine)
- rewriting tag names (e.g. shortening very long function names or adding essential information - like arity for Erlang/Elixir)
- some other uses

Commit is here https://github.com/majutsushi/tagbar/commit/990d79aaf66175fe7d52d47b58d6180cb1fea7b2 

If you are okay with that - there is PR for that https://github.com/majutsushi/tagbar/pull/368

**Comment by majutsushi** [comment]
As I mentioned in the pull request, this is something I would certainly be interested in, but I would like to do some refactoring first. But since there's no need to have two different issues about the same thing I'm going to close this one.
