### ISSUE TITLE
Autocommand nesting too deep

### ISSUE THREAD

**Issue by j5shi** [majutsushi/tagbar#382]
Whenever I execute `:TagbarToggle`, I got:

```
Error detected while processing function tagbar#RestoreSession[1]..<SNR>128_RestoreSession[12]..<SNR>128_goto_win:
line   10:
E218: autocommand nesting too deep
E218: autocommand nesting too deep
E218: autocommand nesting too deep
E218: autocommand nesting too deep
Error detected while processing function tagbar#RestoreSession[1]..<SNR>128_RestoreSession[21]..<SNR>128_InitWindow:
line    5:
E218: autocommand nesting too deep
Error detected while processing function tagbar#RestoreSession[1]..<SNR>128_RestoreSession[12]..<SNR>128_goto_win:
line   10:
E218: autocommand nesting too deep
E218: autocommand nesting too deep
E218: autocommand nesting too deep
E218: autocommand nesting too deep
Error detected while processing function tagbar#RestoreSession[1]..<SNR>128_RestoreSession[21]..<SNR>128_InitWindow:
line    5:
E218: autocommand nesting too deep
```

Could you please give me some advice to debug?

**Comment by majutsushi** [comment]
There must be something odd going on with your setup. `tagbar#RestoreSession()` is only supposed to execute during the `SessionLoadPost` autocommand. Are you loading a session somewhere? Do you have any autocommands in your vimrc that involve sessions or Tagbar?

**Comment by j5shi** [comment]
I got this, did it cause the issue?

```
airline  SessionLoadPost
    *         call <sid>on_window_changed()
	Last set from C:\Program Files (x86)\vim\vimfiles\bundle\vim-airline\plugin\airline.vim
```

**Comment by majutsushi** [comment]
Not by itself, at least I am not able to reproduce the issue in a clean Vim with both Tagbar and Airline installed. So there must be something else in your setup, or some specific thing that you do, that triggers it.

**Comment by j5shi** [comment]
It's been confirmed that the problem is caused by the following autocmd:

```vim
"NOTE: this autocmd WILL cause problem of tagbar
au BufWinEnter,BufReadPost,BufEnter * if expand("%") != "" | silent loadview | endif
```
which tries to restore the view previously saved by:

```vim
"NOTE: this autocmd will not cause problem of tagbar
au BufWinLeave,BufWritePost,BufLeave * if expand("%") != "" | silent mkview! | endif
```

Any suggestion to resolve it? Thanks.

**Comment by majutsushi** [comment]
Sorry for the late reply, and thanks for the additional information. I was able to reproduce it and managed to fix it now I think.

**Comment by majutsushi** [comment]
By the way, it would probably be a good idea to change your autocommands slightly to also check the `buftype` option. This option is generally set for buffers that are managed by plugins, and those plugins might get confused when and older view gets restored.

So the autocommands would then look like this:
```
au BufWinLeave,BufWritePost,BufLeave * if expand("%") != "" && &buftype == "" | silent mkview! | endif
au BufWinEnter,BufReadPost,BufEnter * if expand("%") != "" && &buftype == "" | silent loadview | endif
```

**Comment by j5shi** [comment]
Tried and it works, thank you.
