### ISSUE TITLE
HandleBufDelete aborts with errors

### ISSUE THREAD

**Issue by jpmv27** [majutsushi/tagbar#383]
When using tagbar along with other vim plugins, some operations can cause `HandleBufDelete` to fail. The plugins are BufExplorer and vim-project

Relevant (maybe) configuration:
- set hidden
- set switchbuf=usetab

SCENARIO 1 (vim-project)
- Open a C file in a buffer: `:e file.c`
- Toggle tagbar on
- In window of C file buffer, issue `:Welcome` command
- Result: `E937: Attempt to delete a buffer that is in use`

SCENARIO 2 (BufExplorer)
- Open a C file in a buffer: `:e file1.c`
- Open a second C file in a second buffer in the same window: `:e file2.c`
- Toggle tagbar on
- In window of C file buffer, issue `:BufExplorer` command
- Result: `E93: More than one match for [BufExplorer]`

In both cases, `HandleBufDelete` is called by a `BufDelete` autocmd triggered as a result of the plugin executing `set nobuflisted`.

Please refer to PR #384. This work-around avoids these errors, and doesn't seem to cause any other issues, but I'm not sure whether this is a legitimate fix.

**Comment by majutsushi** [comment]
I guess this can be closed now as well.
