### ISSUE TITLE
:bdel with multiple buffers confuses tagbar

### ISSUE THREAD

**Issue by jpmv27** [majutsushi/tagbar#385]
Relevant (maybe) configuration:
-    set hidden
-    set switchbuf=usetab

Steps to reproduce:
- Open C file in buffer: `:e file1.c`
- Toggle tagbar on
- Open second C file in same window as the first file: `:e file2.c`
- Open third C file in same window as the second file: `:e file3.c`
- Delete buffer for third C file: `:bdel`

Expected result:
- File window shows file2.c content
- tagbar window shows file2.c information

Actual result:
- File window shows file2.c content
- tagbar window shows file3.c information

Even after toggling tagbar off and back on, tagbar still shows file3.c information
The problem doesn't seem to happen if only two files are opened instead of three

**Comment by majutsushi** [comment]
Should be fixed now. At first this looked like a weird side-effect of something the Vim documentation advises against (switching buffers during a `BufDelete` event), but it turned out to just be a global variable changing between uses.
