### ISSUE TITLE
Airline + Tagbar causing Key not present in Dictionary: kinds

### ISSUE THREAD

**Issue by dnyaneshgate** [majutsushi/tagbar#388]
I am beginner in using neovim. I have installed tagbar+airline plugin and getting following error messages frequently.

```
Error detected while processing function <SNR>124_AutoUpdate[52]..<SNR>124_ProcessFile[26]..314:
line   28:
E716: Key not present in Dictionary: kinds  
E15: Invalid expression: a:typeinfo.kinds 
```

Here I have attached vim log file.
[myVimLog.txt](https://github.com/majutsushi/tagbar/files/704102/myVimLog.txt)

**Comment by majutsushi** [comment]
This (and probably #389) are almost certainly caused by https://github.com/neovim/neovim/issues/5817, which has already been reported as #386 . So unless you can reproduce them with normal Vim I'm going to close them as duplicates.
