### ISSUE TITLE
[question] How to get list of function and variables for other plugins?

### ISSUE THREAD

**Issue by rawaludin** [majutsushi/tagbar#390]
Currently I'm using tagbar with PHP. It works perfectly.
I want to pass tagbar functions to fzf so I can filter the method easily. I want to do the same for variables.

How to get list of those in vimrc script?

Thanks.. :)

<img width="387" alt="screen shot 2017-01-19 at 12 04 56 am" src="https://cloud.githubusercontent.com/assets/1274849/22074437/f5bdd954-ddda-11e6-94b1-503d6fa9faa3.png">

<img width="392" alt="screen shot 2017-01-19 at 12 05 04 am" src="https://cloud.githubusercontent.com/assets/1274849/22074452/ffbe479a-ddda-11e6-8c54-25c70b478fbb.png">

**Comment by wsdjeg** [comment]
@rawaludin why do not use unite-outline?
Btw, you can try with SpaceVim. 😄 

fuzzy match + preview windows
![2017-01-20-00 04 42](https://cloud.githubusercontent.com/assets/13142418/22114409/53e3ab84-dea4-11e6-9bce-02bf4391dd1a.png)

**Comment by majutsushi** [comment]
Tagbar is not meant as a library for other plugins, and even if it were it would only support some of what fzf (and CtrlP) need. I am currently working on extracting the lower-level ctags parts into a separate library that other plugins can then depend on, but it's going to be a while until that's ready. So I'm going to close this as a Tagbar issue now, but the general idea should become available as its own plugin later.

**Comment by wsdjeg** [comment]
@majutsushi
Can you add async feature? I like tagbar, but if the file is too large, it take too long time to generate tags.
