### ISSUE TITLE
recognize the methods

### ISSUE THREAD

**Issue by sphynx79** [majutsushi/tagbar#407]
In ruby not recognize the methods

ctags --version:
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 10 2017, 13:33:34
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +multibyte, +case-insensitive-filenames

This is my code:
![image](https://cloud.githubusercontent.com/assets/5004160/23977545/11adfd48-09ef-11e7-9723-d375138c2ede.png)

**DEBUG** 
[tagbardebug.txt](https://github.com/majutsushi/tagbar/files/846398/tagbardebug.txt)

**OUTPUT** 
[tagbardebug_ctags_out.txt](https://github.com/majutsushi/tagbar/files/846400/tagbardebug_ctags_out.txt)

 In this momenti i solved, this problem edit your autoload/tagbar.vim
![image](https://cloud.githubusercontent.com/assets/5004160/23977680/d2db0c22-09ef-11e7-936c-0891b0801659.png)
become
![image](https://cloud.githubusercontent.com/assets/5004160/23977906/46d0d7dc-09f1-11e7-8027-33de4684562e.png)

![image](https://cloud.githubusercontent.com/assets/5004160/23977823/d05d7b00-09f0-11e7-801e-99bc59fe1d1f.png)

I have same problem with ripper-tag and original ctags.

**Comment by majutsushi** [comment]
This is an unfortunate side-effect of how ctags reports its scopes. There isn't really a good quick fix, but I have some longer-term changes planned that should solve this issue (among others).

**Comment by majutsushi** [comment]
I just wanted to note that the change you made will probably result in tags appearing in the wrong scope if they are within a module or function scope, so I would advise against it.

**Comment by LunarLanding** [comment]
@majutsushi I'm using universal-ctags. Their ruby parser has been modified; I haven't found issues by using the modifications above. Can you provide a minimal example of a bug introduced by this modification?

**Comment by jdsutherland** [comment]
Any updates on this front? I concur with @LunarLanding in my usage so far.

**Comment by majutsushi** [comment]
Thanks for letting me know about the updated parser, it seems to fix the problems I described above. I have now been able to properly update the Ruby definition for Universal Ctags after separating the definitions for both programs, so this issue should be fixed now.
