### ISSUE TITLE
Can not work with jsctags 

### ISSUE THREAD

**Issue by donglaizhang** [majutsushi/tagbar#409]
Hey ,

I installed jsctags and generated the tag file with this command line:
`find . -type f -iregex ".*\.js$" -not -path "./node_modules/*" -exec jsctags {} -f \; | sed '/^$/d' | sort > /opt/tag/tags` 
When I open a javascript file, Ctrl+] and Ctrl+T(jsctags) work very well.
After that, I tried to install and use tagbar: 

>1. installed tern_for_vim and tagbar( master branch), 
>2.set the tag path by 
   `let g:tagbar_ctags_bin = '/opt/tag/'` in ~/.vimrc
>3.tried `:Tagbar` and `TagbarToggle` in vim, but vim showed the error: "Exuberant ctags not found at '/opt/tag/'!"

I tried TagbarDebug, please the log: 

> 2017-03-28 16:56:57.448818: ToggleWindow called
> 2017-03-28 16:56:57.449089: OpenWindow called with flags: ''
> 2017-03-28 16:56:57.450027: Checking for Exuberant Ctags
> 2017-03-28 16:56:57.450204: Tagbar: Exuberant ctags not found at '/opt/tag/'!
>                                              2017-03-28 16:56:57.450393: ToggleWindow finished

Env:
Macos 10.11.3
Vim 7.3
Python 2.7
Node v6.5.0

Would you help me to figure out how to solve this problem?

Best Regards,
Donglai

**Comment by xc1427** [comment]
`g:tagbar_ctags_bin` is to explicitly set ctags **executable** location. If ctags is already included in the $PATH, it is not necessary to configure this variable.

Personnally, I do not use jsctags. I use _universal ctags_ and it works OK with modern javascript syntax.

**Comment by donglaizhang** [comment]
Thanks, @xc1427, and let me try ctags for javascript later.

**Comment by majutsushi** [comment]
If you do want to use jsctags you would have to configure it as described here:
https://github.com/majutsushi/tagbar/wiki#jsctags-depends-on-tern--recommended-
