### ISSUE TITLE
Custom ctags patterns

### ISSUE THREAD

**Issue by xahon** [majutsushi/tagbar#411]
How can i include my custom `~/.ctags` preferences for tags generating in tagbar?

**Comment by majutsushi** [comment]
The values in that file should be automatically picked up by ctags, except for the options that Tagbar has to change explicitly either for it to work or because of type-specific configuration.

Is there anything specific that you think is not being picked up by ctags?

**Comment by xahon** [comment]
I paste angular ctag patterns in `~/.ctags`, but tagbar won't show them. But tags file contents angular functions

**Comment by eldamir** [comment]
Similar problem for my custom tsx config in `~/.ctags`

```
--langdef=typescript
--langmap=typescript:.ts.tsx
--regex-typescript=/^[ \t]*(export)?[ \t]*class[ \t]+([a-zA-Z0-9_]+)/\2/c,classes/
--regex-typescript=/^[ \t]*(declare)?[ \t]*namespace[ \t]+([a-zA-Z0-9_]+)/\2/c,modules/
--regex-typescript=/^[ \t]*(export)?[ \t]*module[ \t]+([a-zA-Z0-9_]+)/\2/n,modules/
--regex-typescript=/^[ \t]*(export)?[ \t]*function[ \t]+([a-zA-Z0-9_]+)/\2/f,functions/
--regex-typescript=/^[ \t]*export[ \t]+var[ \t]+([a-zA-Z0-9_]+)/\1/v,variables/
--regex-typescript=/^[ \t]*var[ \t]+([a-zA-Z0-9_]+)[ \t]*=[ \t]*function[ \t]*\(\)/\1/v,varlambdas/
--regex-typescript=/^[ \t]*(export)?[ \t]*(public|protected|private)[ \t]+(static)?[ \t]*([a-zA-Z0-9_]+)/\4/m,members/
--regex-typescript=/^[ \t]*(export)?[ \t]*interface[ \t]+([a-zA-Z0-9_]+)/\2/i,interfaces/
--regex-typescript=/^[ \t]*(export)?[ \t]*type[ \t]+([a-zA-Z0-9_]+)/\2/i,types/
--regex-typescript=/^[ \t]*(export)?[ \t]*enum[ \t]+([a-zA-Z0-9_]+)/\2/e,enums/
--regex-typescript=/^[ \t]*import[ \t]+([a-zA-Z0-9_]+)/\1/I,imports/
```

**Comment by majutsushi** [comment]
If you want to define a new language you have to create a corresponding Tagbar configuration as explained in `:h tagbar-extend`, so that it knows how to interpret the ctags output.
