### ISSUE TITLE
tagbar status update is too slow

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [majutsushi/tagbar#413]
In a java file, when the cursor at tagbar window, while the cursor point at a method, tagbar will show the full method signature at status line, it's useful but it takes about 5 seconds to update to a new method when i move the cursor. Same problem at airline's status which will show method name when the cursor at the edit file buffer.

**Comment by majutsushi** [comment]
The delay depends on Vim's `'updatetime'` option. You can set it to a lower value to have Tagbar update more quickly.

**Comment by skarone** [comment]
I couldn't find 'updatetime' in the entire source code...can you provide an example?

**Comment by FinallyFinancialFreedom** [comment]
@skarone in vimrc,set updatetime=500, the default value is 5000

**Comment by skarone** [comment]
Thanks

**Comment by kflu** [comment]
updatetime is a vim system setting used by other things too. I'm worried this could have adverse effect on performance. Would love to see a tagbar specific global variable for this purpose.

**Comment by alerque** [comment]
I'd be happy to accept a contribution for a tagbar specific *override*, but I think following the generic VIM setting by default is the best thing to do. Changing the value is customary on systems with performance limitations and respecting them by default seems like it is in those people's best interest. They shouldn't have to track down plugin specific settings for every plugin with such a loop. If you really find utility in having the vim setting one thing and tagbar another we can consider an override (properly documented of course).
