### ISSUE TITLE
lost mouse focus when tagbar window is small

### ISSUE THREAD

**Issue by akahanaton** [majutsushi/tagbar#414]
Hi, very happy with the tagbar plugin, thanks a lot.
but when I use it in my 27" screen, it seems the tagbar window cann't get the mouse focus, the tagbar window can't response the mouse event like click or scroll. When I decrease the size of vim edit window to enlarge the tagbar window like this:
:vertical res -150
then the tagbar window can detect the mouse event when its window size took half of the screen size. So its this a bug or is there any options I can set to get it work when its window is small?

thank you very much.

**Comment by majutsushi** [comment]
Are you using Vim in a terminal? If yes then this is a terminal issue. Have a look at `:h 'ttymouse'` and see if you can make it work with one of the settings there.

**Comment by akahanaton** [comment]
Hi majutsushi 
Thanks for you replay, now I'm using vim within tmux, the windows sizes can be easily  re-assigned, so it temporarily solved my problem now, thanks a lot

**Comment by majutsushi** [comment]
Great, I'm going to close this then.
