### ISSUE TITLE
Why don't show tags?

### ISSUE THREAD

**Issue by gHashTag** [majutsushi/tagbar#416]
.vimrc
`Plug 'majutsushi/tagbar'`
`let g:tagbar_ctags_bin='/usr/local/bin/ctags'`
`nmap <F8> :TagbarToggle<CR>`
![2017-04-27 7 04 16](https://cloud.githubusercontent.com/assets/6774813/25467639/361547c8-2b18-11e7-87be-a6e8e91961f3.png)

**Comment by majutsushi** [comment]
You should install jsctags to get good tags for Javascript files. Here are are instructions on how to do that: https://github.com/majutsushi/tagbar/wiki#jsctags-depends-on-tern--recommended-

**Comment by majutsushi** [comment]
Alternatively you can give [Universal Ctags](https://github.com/universal-ctags/ctags) a try, but since I don't really use Javascript myself I don't know which might work better for you.
