### ISSUE TITLE
Method pseudo-tags in es6 files

### ISSUE THREAD

**Issue by nkgm** [majutsushi/tagbar#421]
Just wondering how to go about this as I'm not sure if this is a bug or standard behavior.

When there's more than one methods in a class, pseudo-tags will be displayed for all methods but the first. 

This file for example:
```js
class Point2 {
  constructor(x, y) { this.x = x; this.y = y }
  plus(pt) {
    this //: Point2
    pt //: Point2
    return new Point2(this.x + pt.x, this.y + pt.y)
  }
  minus(pt) {
    this //: Point2
    pt //: Point2
    return new Point2(this.x - pt.x, this.y - pt.y)
  }
  get xx() { return this.x }
  quux() { return 1 }
  static origin() { return new Point2(0, 0) }
}
```
Will produce this (jsctags):
![image](https://user-images.githubusercontent.com/5631881/26876398-a950a9a8-4b8e-11e7-873e-2ae39c3e0b58.png)

As you can seen there's `plus*` and `plus`. Hitting `<CR>` on `plus*` has no effect.

Is this a bug or something that can be configured? Also, would it be possible to display methods in a simpler form eg `plus: Point2 function(pt)` or similar?

**Comment by majutsushi** [comment]
This should be fixed now. It looks like the tern-based jsctags needs a slightly different config from the old, deprecated one.

I'm not sure what you mean by "simpler form". Tagbar simply uses the type that jsctags outputs for the function, so that may have to be changed in jsctags.

**Comment by nkgm** [comment]
Thanks so much for fixing this. 

By "simpler form" I mean not having a foldable namespace for each method that receives args. For example, `minus` above could be displayed in a single line as:
```
minus : Point2 function(?)
```
without the extra `pt : namespace`.
