### ISSUE TITLE
cycle through multiple windows

### ISSUE THREAD

**Issue by nickelchen** [majutsushi/tagbar#428]
Hi, I have this settings in my .vim/vimrc file
`nnoremap <Leader>w <C-w>w` 

what I want is to use `<Leader>w` to cycle through windows, it works perfectly.
When tagbar window shows up, I can use `<Leader>w` to locate the tagbar window, but then can't jump back using same shortcut key `<Leader> w`. Using `<C-w>w` works fine. am I missing some settings ?

**Comment by heshiyou** [comment]
same problem.

**Comment by heshiyou** [comment]
@nickelchen The issue is caused by the key mapping, tagbar use <Space> key to show prototype of tags, you can switch the key map by: 

`let g:tagbar_map_showproto = '<Your key>'`

**Comment by nickelchen** [comment]
@heshiyou That's it ! thank you,  you are a genius.
