### ISSUE TITLE
Latest commit fef0732 fails opening :Tagbar on some javascript files

### ISSUE THREAD

**Issue by unclechu** [majutsushi/tagbar#431]
Minimal javascript file to reproduce it:
```javascript
const x = 1;
const y = 2;
```
My minimal Vim config where I could reproduce it is just empty, only the Tagbar extracted there.
When I try to open `:Tagbar` I get this error:
```text
Error detected while processing function tagbar#ToggleWindow[2]..<SNR>24_ToggleWindow[9]..<SNR>24_OpenWindow[83]..<SNR>24_AutoUpdate[63]..<SNR>24_ProcessFile[110]..13[2]..tagbar#sorting#sort[6]..<SNR>30_compare_by_kind:
line    3:
E716: Key not present in Dictionary: v
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: v
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
```
Tagbar commit: fef07323944f61c20722c006e194b9f84442fa98
I reproduced it on:
* VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  7 2017 13:04:58)
* NVIM v0.2.0
When I checkout to 2abcbf33f05b3455ade1a73e50b5c5803db0e900 (previous commit) this error is disappeared and everything is fine.

**Comment by majutsushi** [comment]
Sorry, I forgot to test the jsctags definition when refactoring.
