### ISSUE TITLE
Wrong object's line with vim-go and gotags

### ISSUE THREAD

**Issue by imilo** [majutsushi/tagbar#439]
I've installed **vim-go** with all needed binaries, added **tagbar** plugin, **gotags** and **ctags** binaries exist in may $PATH.

If I use a provided Vim configuration from `https://github.com/jstemmer/gotags#vim-tagbar-configuration`:
```
let g:tagbar_type_go = {
	\ 'ctagstype' : 'go',
	\ 'kinds'     : [
		\ 'p:package',
		\ 'i:imports:1',
		\ 'c:constants',
		\ 'v:variables',
		\ 't:types',
		\ 'n:interfaces',
		\ 'w:fields',
		\ 'e:embedded',
		\ 'm:methods',
		\ 'r:constructor',
		\ 'f:functions'
	\ ],
	\ 'sro' : '.',
	\ 'kind2scope' : {
		\ 't' : 'ctype',
		\ 'n' : 'ntype'
	\ },
	\ 'scope2kind' : {
		\ 'ctype' : 't',
		\ 'ntype' : 'n'
	\ },
	\ 'ctagsbin'  : 'gotags',
	\ 'ctagsargs' : '-sort -silent'
\ }
```
.. mostly all locations are detected incorrectly, even when selecting a **main()** func. I'm forwarded to some strange line.

**gotags** from shell works fine for the same file, all lines numbers are detected correctly.

If I use your configuration:
```
let g:tagbar_type_go = {
    \ 'ctagstype': 'go',
    \ 'kinds' : [
        \'p:package',
        \'f:function',
        \'v:variables',
        \'t:type',
        \'c:const'
    \]
\}
```
.. most of things works, but variables and consts locations are a little wrong (some lines above) - still not perfect and too less information (no imports, methods, fields, etc.)

How do I make it work properly?

**Comment by imilo** [comment]
Thanks to the other issue (`https://github.com/jstemmer/gotags/issues/31`) I've found out, that a character `^` in a source code breaks everything, if I remove it - tagbar jumps to the correct line everywhere

**Comment by majutsushi** [comment]
I've fixed the main issue in Tagbar, and I've added a comment to https://github.com/jstemmer/gotags/issues/31 to suggest using an actual pattern in the gotags output.
