### ISSUE TITLE
Question: Are ctags auto-generated for current buffer?

### ISSUE THREAD

**Issue by jamischarles** [majutsushi/tagbar#443]
Great plugin! I'm trying to experiment with https://github.com/bengl/btags to generate tags to display in tagbar.

This isn't really an isssue, it's more of a question to understand how tagbar works. I already read through the docs and have a question.

I was using vim-gutentags with tagbar, but disabled vim-gutentags to try btags above instead.

1) My assumption is that Tagbar reads from the `tags` file at the root of the project. However, manually updating the `tags` file or deleting the tags file seems to have no effect on tagbar. It always shows the same output now for my js file. Is there a cache somewhere I'm unaware of?

Or does it automatically generate ctags for the current buffer? Anyway to disable this, so it'll respect the tags file? 

Everything is really accurate for my JS file expect for 2 pseudo tags. Any way to just disable the pseudo tags and hide them?

**Comment by jamischarles** [comment]
I think I'm realizing that pseudo tags is how tagbar is showing nested items.

```js
  class testing { 
   render() {
        var my_obj = {
            first: 'hello',
            second: 'hello'
        }
}
```
Shows up in tagbar as:
```
testing : class
  render() : method

myObj* : class
  first : property
  second : property

```
I'm assuming what's happening here is that ctags is unable to determine that the object in the method is a child of the method. Is that accurate?

**Comment by jamischarles** [comment]
After reading the "exending tagbar" section more closely, it looks like I can swap out my own tag generator by file type that way. I think that'll solve my problems, assuming that ctags really is the culprit above.

Final question: Is it safe to assume that since tagbar auto-generates tags for the current buffer, it completely ignores the `tags` file?

**Comment by majutsushi** [comment]
Yes, Tagbar never reads `tags` files and always generates the tags on the fly by executing the configured tag-generating programs. Otherwise keeping the information up-to-date would require either a lot of additional complexity in Tagbar, or it would require a dependency on another plugin that takes over that task. But since generating the tags for a single file is generally very fast the disadvantages have so far outweighed the advantages.

If the btags output is different from the jsctags/Exuberant Ctags output then using it as a drop-in replacement is not going to work and you will have to define a btags-specific configuration for Tagbar, otherwise the display will not be correct. Pseudotags, as explained in `:h tagbar-pseudotags`, are tags that are referenced as "parent scope" tags by other tags (i.e. their children), but that do not exist as a tag themselves in the output. This happens for example with anonymous namespaces or structs in C/C++. So in your case it looks like the `myObj` class did not actually appear in the btags output as its own tag. But since I don't know anything about btags I don't know what the reason for that could be.

**Comment by jamischarles** [comment]
Thank you for the detailed answer. That really helps.

As far as I can tell btags output tries to match ctags output fairly closely (I could be wrong though):

```tags
!_TAG_FILE_FORMAT	2	/extended format/
!_TAG_FILE_SORTED	0	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Bryan English	/bryan@bryanenglish.com/
!_TAG_PROGRAM_NAME	btags	//
!_TAG_PROGRAM_URL	http://github.com/bengl/btags	/github repository/
!_TAG_PROGRAM_VERSION	1.0.1	//
React	public/js/components/Conversion.js	1;"	i
PropTypes	public/js/components/Conversion.js	2;"	i
axios	public/js/components/Conversion.js	3;"	i
debounce	public/js/components/Conversion.js	4;"	i
	public/js/components/Conversion.js	8;"	v
conversion	public/js/components/Conversion.js	10;"	v
render	public/js/components/Conversion.js	7;"	f	class:FeesTable
FeesTable	public/js/components/Conversion.js	6;"	c
constructor	public/js/components/Conversion.js	43;"	f	class:Conversion
componentDidMount	public/js/components/Conversion.js	64;"	f	class:Conversion
```

Assuming btags output is similar enough, (or that I could provide output that is similar enough), is there an easy place to tell tagbar to use btags instead?

Also, regarding the pseudo-tags, currently tagbar shows this:
```tags
▼ Conversion : class
    _makeConversionAjaxCall(data, successCallback, failureCallback) : method
    _makeFeeAjaxCall(payload, successCallback, failureCallback) : method
    calcNewTotal() : method

▼ _makeConversionAjaxCall* : class
  ▼ payload : class
      calcOriginAmount : property
      destAmount : property
```

Above `_makeConversionAjaxCall` is first listed as a child of `Conversion` class, but when `_makeConversionAjaxCall` itself and it's children are listed as a pseudo tag (class)? Is this a ctags problem not parsing the javascript properly, or am I misunderstanding how it works?


Here's the JS for the above tags
```js
class Conversion extends React.Component {
    constructor(props) {
        this.state = {
            [...]
        }
    }

    _makeConversionAjaxCall(data, successCallback, failureCallback) {
        var payload = {
            destAmount: data.newValue || this.state.destAmount,
            calcOriginAmount: false
        }
    }
}
```

**Comment by majutsushi** [comment]
I've had a quick look at the btags source code, and the problem seems to simply that its output is slightly different from the output of the currently supported Javascript parsers. I did a quick test, and this configuration (in `~/.vimrc`) seems to work for me:

```vim
let g:tagbar_type_javascript = {
    \ 'replace' : 1,
    \ 'kinds' : [
        \ 'c:classes',
        \ 'f:functions',
        \ 'v:variables',
        \ 'i:imports',
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 'c' : 'class',
    \ },
    \ 'ctagsbin' : 'btags',
    \ 'ctagsargs' : ''
\ }
```

**Comment by jamischarles** [comment]
This is perfect! Thank you so much. I was having a hard time grokking the config of `tagbar_type_javascript` in tagbar-extend docs.

Final question: If I could make the output of btags was identical to ctags output, then I could just use these 2 lines right?
```
 \ 'ctagsbin' : 'btags',
 \ 'ctagsargs' : 
```

**Comment by majutsushi** [comment]
Yes, if the output is actually identical, then those two lines should be enough (provided you don't have jsctags in your `PATH` as well, because that will automatically load a different configuration).

**Comment by jamischarles** [comment]
Yeah, I found that out the hard way haha. I had jsctags installed and couldn't figure out for the life of me why it was showing something other than the ctags output.

**Comment by majutsushi** [comment]
That behaviour is there so that people don't have to explicitly configure jsctags after installing it. I have some ideas about making theses things a bit more clear in the default configuration, but it's not finished yet.

So can this issue be closed then?

**Comment by jamischarles** [comment]
Yep. Thanks for all your help 👍
