### ISSUE TITLE
Question : How to start vim with TagBar

### ISSUE THREAD

**Issue by sebma** [majutsushi/tagbar#448]
Hi,

I want to start vim with TagBar so I added `TagbarOpen` in my `.vimrc` but when run vim, it says : 

`E492: Not an editor command: TagbarOpen`

Can you help me ?

**Comment by majutsushi** [comment]
That's because `.vimrc` is read before any of the plugins has been loaded. How to automatically open Tagbar is explained in `:h tagbar-autoopen`.

**Comment by sebma** [comment]
@majutsushi Thanks a lot :)

**Comment by sebma** [comment]
@majutsushi How do I check in my `vimrc` if Exuberant Ctags or Universal Ctags is installed before calling the `tagbar#autoopen(1)` ?

**Comment by majutsushi** [comment]
You could use Vim's `executable()` function.

**Comment by sebma** [comment]
@majutsushi Thanks, I'll look into has soon as I have the time.
