### ISSUE TITLE
CloseWindow() will change other windows size

### ISSUE THREAD

**Issue by waruqi** [majutsushi/tagbar#452]
Before closing tagbar window:

![snip20171020_4](https://user-images.githubusercontent.com/151335/31801603-ecaac87a-b50e-11e7-9eaf-067042a21dee.png)

After closing tagbar window:

![snip20171020_5](https://user-images.githubusercontent.com/151335/31801614-f5981546-b50e-11e7-8a92-d3ef9240d3c7.png)

The height of bottom terminal windows has been changed.

```vim
function! s:CloseWindow() abort

    if &equalalways
        wincmd =    <--  this code line will change other windows size
    endif

endfunction
```

And it works fine if I remove `wincmd =`

**Comment by majutsushi** [comment]
Thanks for the report, I've moved that part of the code to the more specialized use case where it's actually needed.
