### ISSUE TITLE
Sometimes tags are not highlighted when tagbar_show_visibility = 0

### ISSUE THREAD

**Issue by hanschen** [majutsushi/tagbar#463]
After `let g:tagbar_show_visibility = 0`, Tagbar sometimes does not highlight certain tags. For example for the Python file
```
def tagbar():
    return
```
Tagbar will show
```
" Press <F1>, ? for help
 
 +tagbar : function
```
by default, with `tagbar` being highlighted. Setting `let g:tagbar_show_visibility = 0`, Tagbar shows
```
" Press <F1>, ? for help
 
 tagbar : function
```
without the highlighting.

I suspect the issue is due to a missing space. I can "fix" it by making sure `prefix` ends with a space after this if statement:

https://github.com/majutsushi/tagbar/blob/460f3c8f2eb2e80a0109f6c40599502ee8a9303c/autoload/tagbar/prototypes/basetag.vim#L86

**Comment by majutsushi** [comment]
Thanks, this was actually a bug in the highlight pattern. it didn't account for the fact that the space for the visibility symbol may not be there at all. It should work correctly now.
