### ISSUE TITLE
tagbar - vim-airline integration issue

### ISSUE THREAD

**Issue by devakivamsi** [majutsushi/tagbar#472]
I use vim with tags file defined in my vimrc.
After launching vim using "vim -t some_tag_name" statusline looks as expected.
<img width="565" alt="screen shot - vim -t main" src="https://user-images.githubusercontent.com/8160763/35075843-41f7af0a-fbaa-11e7-8b84-1b1f8d78cd3e.png">

A "CRTL-L" (or any scrolling to different page that causes redraw) will revert statusline to default vim looks.
<img width="567" alt="screen shot - ctrl-l" src="https://user-images.githubusercontent.com/8160763/35075844-4215876e-fbaa-11e7-9907-20a354359739.png">

If i remove the tagbar plugin, the issue goes away. I see the issue even when using default tagbar & airline configurations.

Vim version: 7.4
vim-airline: 0.9 (e02176aca15905e80dbb38de2a53416cf6460cfe)
tagbar: Latest as of Jan 17th 2018 (387bbadda98e1376ff3871aa461b1f0abd4ece70)

**Comment by alerque** [comment]
I am unable to reproduce this in either VIM 8 or Neovim as of this time. If anybody else can and can help out with a MWE that causes this I'd be happy to give it another go.

**Comment by devakivamsi** [comment]
I don't see this in Vim 8.2. Closing.
