### ISSUE TITLE
import statement and try

### ISSUE THREAD

**Issue by hholst80** [majutsushi/tagbar#473]
Repro:

```
from __future__ import print_function

try:
    import snappy
except:
    print('Failed to import snappy. THIS WILL TURN UP IN TAGBAR AS IMPORTS')
```

It seems everything to the right of the word `import` in the print statement will turn up in the tagbar.

**Comment by alerque** [comment]
This is a bug in whatever tag parser you are using, not tagbar itself. Are you using a reasonably new version of Universal Ctags? That should resolve this. If not a bug should reported to that project as it is incorrectly parsing the source.

Tagbar doesn't actually parse the source, it just reads the parsed output from `ctags`.

If there is any other way we can help please do let us know!
