### ISSUE TITLE
Hide line numbers on tagbar

### ISSUE THREAD

**Issue by Mte90** [majutsushi/tagbar#479]
![screenshot_20180206_220030](https://user-images.githubusercontent.com/403283/35883919-476b8814-0b89-11e8-9811-4200cfa75199.png)

This is what happen on my Vim

**Comment by alerque** [comment]
I've never seen this. Do you have something in your vim config enabling numbering on all file types or when entering buffers or something? We already have some code that turns numbering off in the tagbar window by default so I think you must have some unusual config that is leading to re-enabling it. Can you give us more information to work with here?

**Comment by Mte90** [comment]
After an year seems that this problem is not happening anymore.
