### ISSUE TITLE
Add support for extrawords from C++14 [noexcept, override]

### ISSUE THREAD

**Issue by Posto578** [majutsushi/tagbar#480]
Tagbar does not show function signatures correctly when the function is marked as a _noexcept_ or _override_. Instead of showing full name it prints only a keyword like _noexcept_.

![zrzut ekranu 2018-01-25 o 01 44 52](https://user-images.githubusercontent.com/35492119/35939318-12c448e4-0c4c-11e8-9a44-d3818cb3702d.png)

**Comment by luc1ph3r** [comment]
Turns out, this is [a bug](https://sourceforge.net/p/ctags/bugs/367/) of exuberant ctags.

**Comment by luc1ph3r** [comment]
Seems like [an old bug](https://sourceforge.net/p/ctags/bugs/367/) related to exuberant-ctags.
With [universal-ctags](https://github.com/universal-ctags/ctags) everything is displayed as it should be.

**Comment by alerque** [comment]
This seems like something we can't fix. If anybody does know a way to make exuberant-ctags report this correctly we'd be happy to accept a contribution to this plugin to make it work, but with a decade of bit-rot upstream I think the answer to this question is "use universal-ctags instead", you'll get much better support that way.
