### ISSUE TITLE
TagbarToggle doesn't work with other commands when joined with '|'

### ISSUE THREAD

**Issue by grepinsight** [majutsushi/tagbar#484]
I am trying to move the cursor to the tagbar window by default by using the following command:

```
nmap <F8> :TagbarToggle | <C-w>l <CR>
```

It didn't work.  I realized that `TagbarToggle` in general doesn't work with other commands as well:
For example, following doesn't work:

```
nmap <F8> :TagbarToggle<CR> \| :echo 'hi'<CR>
```

**Comment by alerque** [comment]
This has to do with the way VIM parses commands, not with tagbar per-se. You can use the function calls in this way, just not the commands. Try this instead:

```vim
nmap <F8> call tagbar#ToggleWindow() | ...
```
