### ISSUE TITLE
Problem with tempname()

### ISSUE THREAD

**Issue by taq** [majutsushi/tagbar#498]
Hey, check this out: https://github.com/w0rp/ale/issues/1722#issuecomment-404856755

Tagbar stopped to work after an ALE update, related to `tempname()`. Please check the comments there.

**Comment by w0rp** [comment]
I'll provide a little bit of explanation. `tempname()` doesn't return the right values on some Linux machines when the `TMPDIR` environment variable isn't set. The safest solution is to check `has('unix') && empty($TMPDIR)`, temporarily `let $TMPDIR = '/tmp'`, get the value out of `tempname()`, and then `let $TMPDIR = ''` again. You have to clear the environment variable again, as leaving it set to `'/tmp'` will also break other environments.

**Comment by taq** [comment]
Thanks, @w0rp !

**Comment by taq** [comment]
Ok, seems it was fixed on ALE.

**Comment by w0rp** [comment]
Yep, after a lot of confusion, I have fixed this now.
