### ISSUE TITLE
Tag generators for Elm and Rmarkdown

### ISSUE THREAD

**Issue by MaximeWack** [majutsushi/tagbar#506]
Hi,

I created two python scripts, inspired by https://github.com/vimwiki/utils/blob/master/vwtags.py to handle tags in tagbar for Rmd and Elm files.

I made a [blogpost](https://www.maximewack.com/post/tagbar) showing the two scripts in action.
They can be found as gists here: [elmtags.py](https://gist.github.com/MaximeWack/388c393b7db290dd732f0a2d403118c5) and [rmdtags.py](https://gist.github.com/MaximeWack/cdbdcd373d68d1fe5b3aca22e3dcfe46)

Feel free to reference/include them in the wiki!

**Comment by alerque** [comment]
Please go ahead and add the information about how to support those languages to the wiki yourself! We'd love to see it included, but the most knowledgeable person to document it would be _you_. Thanks for the contribution by the way, I hope it helps others.

**Comment by MaximeWack** [comment]
I didn't notice that the wiki was publicly editable! The info is now in the wiki.
Is there anything to do to trigger DocToc to refresh the TOC?

**Comment by alerque** [comment]
Thanks for the contribution!

I think doctoc has to be run locally by checking out the Wiki as a git repository and running it on your system. I've just done that, so it's up to date now. There were a few other recent changes not reflected in the TOC yet.
