### ISSUE TITLE
Error on toggle

### ISSUE THREAD

**Issue by brentshermana** [majutsushi/tagbar#520]
I get the following error on running `:TagbarToggle`:

```
Error detected while processing function tagbar#ToggleWindow..<SNR>29_ToggleWindow..<SNR>29_OpenWindow..<SNR>29_Init..<SNR>29_InitTypes..tagbar#types#ctags#init:
line  743:
E117: Unknown function: s:createKinddict
```

Configuration details: Ubuntu 14, I have my `g:tagbar_ctags_bin` set to a custom location -> ctags version `Exuberant Ctags 5.8`

**Comment by alerque** [comment]
What filetype are you trying this on? I'm not able to replicate this, and until we're able to see what the actual problem is I won't be able to fix it. I'd be happy to look into it if you gave enough info that we could replicate it, or if you found the issue and submitted a fix so it works for you.

**Comment by brentshermana** [comment]
🤷‍♂ it's been almost a year since I faced the issue (or needed to use vim for work), so if the error message isn't enough to go off of we should probably close this

**Comment by alerque** [comment]
@brentshermana I'm sorry you are no longer able to enjoy vim as part of your work, that would be really rough for me ;-) Thanks for responding with feedback though.

I don't think this is enough information to go on. I'd be happy to fix something that we could reproduce, examine what was wrong, and test that we fixed — but unless and until more info comes up I'm going to close this as un-actionable.

If anybody else runs into the same error feel free to comment here and we'll give it another look!
