### ISSUE TITLE
very slow perfomance in neovim

### ISSUE THREAD

**Issue by zubairakram** [majutsushi/tagbar#527]
tagbar updates after 2 to 3 seconds on saving file. I tried python and c++ code with just one class.
using ```NVIM v0.3.1```.

**Comment by alerque** [comment]
What do you have vim's `updatetime` configured to? Run `:set updatetime` to see, and try lowering this value (in milliseconds) to change it.

If that doesn't fix it for you, please also see #494, of which this issue appears to be a duplicate.
