### ISSUE TITLE
some function can't be showed for C

### ISSUE THREAD

**Issue by chezhai** [majutsushi/tagbar#538]
you can see following:
```
extern int __sigismember(const __sigset_t*, int);
extern int __sigaddset(__sigset_t*, int);
```
those functions are defined in "/usr/include/x86_64-linux-gnu/bits/sigset.h".(this header is system file, only has declaration, but has no definition)

but when i open tagbar, those functions can't be show.

so, what's wrong?

**Comment by alerque** [comment]
I suspect your version of ctags is not reporting anything useful for these definitions. You likely have an old version of exuberant-ctags, please use universal-ctags instead. Once you have that available I think these definitions will get parsed and tags reported for them.

If not please feel free to comment back here and we'll take another look.
