### ISSUE TITLE
Suggestion: autopreview toggle mapping

### ISSUE THREAD

**Issue by elig0n** [majutsushi/tagbar#542]
I would like to suggest the above mapping

**Comment by alerque** [comment]
I don't know what you are asking for here. Could you go into a bit more detail on what you actually want?

**Comment by elig0n** [comment]
Hi I am looking for a key that will serve as a toggle between hide and show of the preview window.

**Comment by alerque** [comment]
If by "preview window" you mean the tag navigator pane, you can use any mapping you want, but you should pick one and set it up to taste in your rc file. For example mine is:

```vim
nmap <leader>t :TagbarToggle<CR>
```

In most setups VIM's default leader key is `\`, so `\` followed by `t` toggles the tagbar window on and off. This is [already documented in the quick start section of the readme](https://github.com/majutsushi/tagbar#quickstart).

Hopefully that answers your question. If you mean something else please clarify.
