### ISSUE TITLE
ctags: Unknown option: --extras, exit code: 1

### ISSUE THREAD

**Issue by ardeidae** [majutsushi/tagbar#552]
Hello,

I've just updated tagbar plugin and it seems to be broken.

```
Tagbar: Could not execute ctags for /Users/me/test.py!
Executed command: "'/usr/local/bin/ctags' '-f' '-' '--format=2' '--excmd=pattern' '--fields=nksSaf' '--extras=' '--file-scope=yes' '--sort=no' '--append=no' '--language-force=python' '--python-kinds=icfmv' '/var/folders/x6/m5n53g_94wd0_t_8hw0cdfw80000gp/T/vapJraw/77.py'"
Command output:
ctags: Unknown option: --extras
Exit code: 1
```

I am on macOS 10.14.6.
ctags is installed with brew.

```
ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 19 2018, 23:32:48
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

How to fix it, please?

**Comment by ardeidae** [comment]
It seems to be related with #502

**Comment by NoevilMe** [comment]
modify tagbar/autoload/tagbar.vim line 1108 '--extras=' into '--extra='

**Comment by ardeidae** [comment]
Sorry, but it's not an acceptable solution.

**Comment by alerque** [comment]
This is another reason we need #551! My testing is using a different version of `ctags` and not showing this up. Personally I would recommend you use universal-ctags anyway as it is better in almost every way (and updated more recently that 2009), but there is no reason for this to stay broken either. I will revert that right away and look for another solution to avoid the deprecation message.

**Comment by felipealfonsog** [comment]
I got it fixed with this: To specify the ctags in 
`$ home/. vimrc.`
`let g:Tlist_Ctags_Cmd='/usr/bin/ctags'`
