### ISSUE TITLE
Golang same package multiple source files

### ISSUE THREAD

**Issue by tiger-regit** [majutsushi/tagbar#554]
How to display all the tags under the same package? In golang, a package can have multiple source files. But the tagbar can only display the tags of the currently open file.

One of the files in the sms package
![image](https://user-images.githubusercontent.com/6560524/67281287-a3007780-f501-11e9-99b2-ec0432dcbff6.png)

One of the files in the sms package
![image](https://user-images.githubusercontent.com/6560524/67281355-c5929080-f501-11e9-9ef5-a362ef22e9a3.png)

**Comment by alerque** [comment]
At this point I don't think *tagbar* has any concept of a "project" or "package" and it is not parsing through directory trees looking for tags, it is just working on the current buffer.

If somebody wants to work on support for such a thing we can probably consider it, but this would be an extensive change.

**Comment by tiger-regit** [comment]
I see, thank you.
