### ISSUE TITLE
Suggestion: Implement live display of ipythons magic command '%whos'

### ISSUE THREAD

**Issue by amenl** [majutsushi/tagbar#566]
Would be a real timesaver to have direct access to certain variables and their respective values.
%whos prints a subset of variables if you add the type of variable (e.g. %whos int); nice would be a selection based on a regex expression. But I'm just dreaming..

**Comment by alerque** [comment]
I can't say I even understand what you are asking here, but I'm happy to consider and review contributions if you (or anybody) wants to make this happen.

**Comment by amenl** [comment]
I admit my suggestion is a little out of context eventually. Not everyone may use Vimux with Ipython. Possibly even worth its own plugin. However I thought a display of all assigned variables (and its values) would integrate nicely in tagbar. Debugging code without starting pdb would be easier.
In terms of contributing to make this happen I can't really say this is likely to happen soon.
