### ISSUE TITLE
Tagbar can't execute ctags under Elvish shell

### ISSUE THREAD

**Issue by vendion** [majutsushi/tagbar#569]
I don't know if you prefer a new ticket in this case or I necro issue #495 (from more than a year ago) but I'm having the same issue.

General information
OS: Arch Linux
Vim Version: 8.1.2268
tagbag commit sha: `a0f51bd`

Vim error message when calling TagBar:

```
Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a
 directory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'/usr/bin/ctags' --version"
Command output is empty.
Exit code: 2
```

Ctag info:

```
[~]─> which ctags
/usr/bin/ctags
[~]─> /usr/bin/ctags --version
Universal Ctags 0.0.0(eda1c6a5), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 10 2019, 14:06:39
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
```

I have explicitly set the `g:tagbar_ctags_bin` variable to point to my ctags binary but it still is erroring out.

**Comment by alerque** [comment]
I'm a little puzzled by this one. I'm an Arch Linux myself and hence that's the primary platform I test on. Your output from `ctags` looks like it should work to me. I'm a little puzzled though as the version hash is not the [current Arch Linux package](https://www.archlinux.org/packages/extra/x86_64/ctags/) for universal-ctags. I'm also mostly testing with Neovim, but I can't see how that would make a difference in this case, and I just checked VIM for good measure.

Given that your default path has ctags in it just fine, I would actually try _not_ setting the bin directory (and hence not potentially introducing an error in quoting, etc.). Also are you sure that `ctags` is the Arch packaged one and not a symlink to a Snap package or something like that? (the Snap version has a known issue with reading temp files, see #568).

**Comment by vendion** [comment]
Okay so part of that seems to be my fault, I had [universal-ctags-git[(https://aur.archlinux.org/packages/universal-ctags-git/) from the AUR installed as the `ctags` package in the extra repo isn't very obvious that it is actually universal-ctags from the package name/description. I switched over to using the version in the extra repo and get the same thing.

```
[~]─> ctags --version
Universal Ctags 0.0.0(3fdf28bc), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 22 2019, 21:51:22
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
[~]─> pacman -Qi ctags
Name            : ctags
Version         : 1:r20190522+g3fdf28bc-1
Description     : Generates an index file of language objects found in source files
Architecture    : x86_64
URL             : https://ctags.io/
Licenses        : GPL
Groups          : None
Provides        : universal-ctags
Depends On      : libxml2  jansson  libyaml  libseccomp
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1065.00 KiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : Wed 22 May 2019 05:51:22 PM EDT
Install Date    : Thu 19 Dec 2019 09:45:00 AM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

```
 Tagbar: Ctags doesn't seem to be Exuberant Ctags!
BSD ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a d
irectory in your $PATH or set g:tagbar_ctags_bin.
Executed command: "'/usr/bin/ctags' --version"
Command output is empty.
Exit code: 2
```

Although the hash reported by `ctags --version` and what is used in the version string in the PKGBUILD file still seems to differ. Originally I did not have the `g:tagbar_ctags_bin` variable set and was still getting this error so I tried setting it to see if would change anything.

Seeing as how it seem that [this check was what was failing](https://github.com/majutsushi/tagbar/blob/master/autoload/tagbar.vim#L409) I was hoping to be able to by pass that check and just have it use the `ctags` binary anyways.

**Comment by alerque** [comment]
> Although the hash reported by ctags --version and what is used in the version string in the PKGBUILD file still seems to differ.

They look the same to me. You know one of them (the PKGBUILD) has git hashes prefixed with "g" right? The hash (`3fdf28bc`) is the same, and also the same as what I have. We're now running _exactly_ the same build binary.

That doesn't explain why tagbar can't seem to execute ctags. Can you try running `:!ctags --version` from inside VIM to see if it's something basic about vim not being able to execute shell commands? Also have you tried disabling any and all _other_ plugins and stripped down to a minimal vim rc?

Somehow vim is coming up with the idea that it found ctags but the output of running `--version` on it gives empty output. With no output to parse it can't guess what version it is and assumes the worst (probably safest given that it won't work even if it's the right ctags but we can't read any output from it!). You don't have vim sandboxed or something like that do you?

**Comment by alerque** [comment]
Also it would really help if you could pass along the full output of a debug log. This might be a shell specific issue (what shell does vim think you ran it inside of by the way?). See `:help tagbar-issues` for instructions on how to get a debug log.

**Comment by vendion** [comment]
>> Although the hash reported by ctags --version and what is used in the version string in the PKGBUILD file still seems to differ.
>
> They look the same to me. You know one of them (the PKGBUILD) has git hashes prefixed with "g" right? The hash (3fdf28bc) is the same, and also the same as what I have. We're now running exactly the same build binary.

/facepalm
Sorry still early and just glanced at the first bit.

> That doesn't explain why tagbar can't seem to execute ctags. Can you try running :!ctags --version from inside VIM to see if it's something basic about vim not being able to execute shell commands?

Doing that I get the same output as I do when running it from the shell, so VIM is at least able to call the executable. 

> Also have you tried disabling any and all other plugins and stripped down to a minimal vim rc?

Stripping my .vimrc down to just a few basic lines and removing all plugins except for tag bar I get the same error.

> Also it would really help if you could pass along the full output of a debug log. This might be a shell specific issue (what shell does vim think you ran it inside of by the way?). See :help tagbar-issues for instructions on how to get a debug log.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2019 22:30:47)
Included patches: 1-2268
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -dnd               +localmap          +profile           +timers
+arabic            -ebcdic            +lua/dyn           +python/dyn        +title
+autocmd           +emacs_tags        +menu              +python3/dyn       -toolbar
+autochdir         +eval              +mksession         +quickfix          +user_commands
-autoservername    +ex_extra          +modify_fname      +reltime           +vartabs
-balloon_eval      +extra_search      +mouse             +rightleft         +vertsplit
+balloon_eval_term -farsi             -mouseshape        +ruby/dyn          +virtualedit
-browse            +file_in_path      +mouse_dec         +scrollbind        +visual
++builtin_terms    +find_in_path      +mouse_gpm         +signs             +visualextra
+byte_offset       +float             -mouse_jsbterm     +smartindent       +viminfo
+channel           +folding           +mouse_netterm     -sound             +vreplace
+cindent           -footer            +mouse_sgr         +spell             +wildignore
-clientserver      +fork()            -mouse_sysmouse    +startuptime       +wildmenu
-clipboard         +gettext           +mouse_urxvt       +statusline        +windows
+cmdline_compl     -hangul_input      +mouse_xterm       -sun_workshop      +writebackup
+cmdline_hist      +iconv             +multi_byte        +syntax            -X11
+cmdline_info      +insert_expand     +multi_lang        +tag_binary        -xfontset
+comments          +job               -mzscheme          -tag_old_static    -xim
+conceal           +jumplist          +netbeans_intg     -tag_any_white     -xpm
+cryptv            +keymap            +num64             +tcl/dyn           -xsmp
+cscope            +lambda            +packages          +termguicolors     -xterm_clipboard
+cursorbind        +langmap           +path_extra        +terminal          -xterm_save
+cursorshape       +libcall           +perl/dyn          +terminfo          
+dialog_con        +linebreak         +persistent_undo   +termresponse      
+diff              +lispindent        +postscript        +textobjects       
+digraphs          +listcmds          +printer           +textprop          
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     2019-12-19 10:35:01.065187: ToggleWindow called
2019-12-19 10:35:01.065301: OpenWindow called with flags: ''
2019-12-19 10:35:01.065429: Checking for Exuberant Ctags
2019-12-19 10:35:01.065693: EscapeCtagsCmd called
2019-12-19 10:35:01.065737: ctags_bin: ctags
2019-12-19 10:35:01.065778: ctags_args (is a string): --version
2019-12-19 10:35:01.067366: Escaped ctags command: 'ctags' --version
2019-12-19 10:35:01.067435: Executing ctags command: 'ctags' --version
2019-12-19 10:35:01.083245: Calling shell to execute: "('ctags' --version) > /tmp/vty7l0w/1"
2019-12-19 10:35:01.083316: Exit code: 2
2019-12-19 10:35:01.101372: Command output:

2019-12-19 10:35:01.101439: Exit code: 2
2019-12-19 10:35:01.101497: Tagbar: Ctags doesn't seem to be Exuberant Ctags!
            2019-12-19 10:35:01.101690: ToggleWindow finished
```

As for the shell I am using the [Elvish](https://github.com/elves/elvish) shell

**Comment by alerque** [comment]
Okay this is going to be a problem specific to Elvish. Note there is a lot of machinery in this plugin for executing shell commands with various arguments and passing various data back and forth to get `ctags` output in various situations. E.g. see:

https://github.com/majutsushi/tagbar/blob/a0f51bd5a6514632bf3d2df1b001df27361892bd/autoload/tagbar.vim#L2673-L2717

Try running `bash` or `sh`, then run vim and see what you get. My money is on it working fine.

I'd be happy to accept a contribution to this project that correctly sets up shell escaping and execution commands for Elvish, but I will likely not get around to doing it myself.

This might be as simple as telling VIM to switch to a different shell internally, as for example we do with `fish` already. You might try copying that.

**Comment by alerque** [comment]
The most obvious culprit is that for sh/bash we are quoting the bin path in _all_ cases (whether it has spaces or not). This works in POSIX shells but must not work in yours. Can you run `'/usr/bin/ctags' --version` from you command prompt (with the quotes)?

**Comment by vendion** [comment]
> Can you run '/usr/bin/ctags' --version from you command prompt (with the quotes)?

Quoting the path like that isn't an issue for Elvish:

```
[~]─> '/usr/bin/ctags' --version
Universal Ctags 0.0.0(3fdf28bc), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May 22 2019, 21:51:22
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
```

I'll see if I can take a look at this over the next week or so and see if I can't get a working PR in place.

**Comment by vendion** [comment]
I just created PR #571 which handles Elvish in the same fashion as is already used with Fish as that approach is clean enough to be maintanable even if it may not be ideal.
