### ISSUE TITLE
Support for Dart

### ISSUE THREAD

**Issue by jrc2139** [majutsushi/tagbar#570]
I'm trying to add Dart to Tagbar.

I'm using [dart_ctags](https://github.com/nerdrew/dart-ctags) for the tags, and they generate these functional [tags](https://pastebin.com/7h1TW2gR).

I've added to the Tagbar config:
```
let g:tagbar_type_dart = {
	\ 'ctagstype' : 'dart',
	\ 'kinds'     : [
		\ 'c:classes',
		\ 'i:types',
		\ 'm:methods',
		\ 'M:constructor',
		\ 'f:functions',
	\ ],
	\ 'ctagsbin'  : 'pub',
    \ 'ctagsargs' : 'global run dart_ctags:tags',
\ }
```

Tagbar is able to run this successfuly, however, I get these error messages in the vim console:

```
Error detected while processing function <SNR>165_AutoUpdate[63]..<SNR>165_ProcessFile[121]..<SNR>169_sortTags[2]..tagbar#sorting#sort[6]..<SNR>173_compare_by_kind:
line    3:
E716: Key not present in Dictionary: c^I
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: f^I
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
```

Here is the [tagbar debug log](https://pastebin.com/28dY0xc8).

Does anyone have any ideas about handling the f^I or c^I missing key errors?

**Comment by alerque** [comment]
Off the top of my head I think you need to have kinds specified for all possible tags even if they aren't ones you use. I'm not sure that's what's happening here but you may need to teach it to ignore some things.

When you do get it figured out I'd be happy to help with a PR to get support for this added upstream.

**Comment by jrc2139** [comment]
@alerque does `f^I` mean a special character in a vim script?  i'm confused because i don't see any corresponding `f^I` in the generated tags.  how could i ignore?

**Comment by jrc2139** [comment]
ok I put up a [PR](https://github.com/nerdrew/dart-ctags/pull/5) for dart_ctags for better tagbar compatibility and look like [gotags](https://github.com/jstemmer/gotags).

**Comment by jrc2139** [comment]
my config currently looks like:

```
let g:tagbar_type_dart = {
    \ 'ctagstype' : 'dart',
    \ 'kinds'     : [
        \ 'c:classes',
        \ 'i:fields',
        \ 'm:methods',
        \ 'M:static methods',
        \ 'C:constructors',
        \ 'f:functions',
        \ 'o:operators',
        \ 'g:getters',
        \ 's:setters',
        \ 'a:abstract functions',
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 'c' : 'class',
    \ },
    \ 'scope2kind' : {
        \ 'class' : 'c',
    \ },
    \ 'ctagsbin'  : 'dart_ctags',
	\ 'ctagsargs' : '-l'
\ }
```

**Comment by jrc2139** [comment]
ok, the [PR](https://github.com/nerdrew/dart-ctags/pull/5) was accepted.  should this just be added to the wiki?

**Comment by alerque** [comment]
Congratulations, and thanks for sending that upstream.

As for this end, adding it to the Wiki just means people have to manually setup support themselves. I would rather see the setup added directly to the core plugin so it works out of the box. The only requirement would be that people install the correct ctags provider.

Would you be willing to take care of that too? I think there are a couple examples already in the source.

**Comment by jrc2139** [comment]
thanks alerque!  that sounds good.  I'll start working on it later this week.

**Comment by alerque** [comment]
Whatever we need to do to make this work out of the box for dart it looks like we need to do the same thing for go. See #573.

**Comment by jrc2139** [comment]
I'll keep that in mind and make a separate PR.

**Comment by jrc2139** [comment]
dart_ctags [PR](https://github.com/majutsushi/tagbar/pull/581) & gotags [PR
](https://github.com/majutsushi/tagbar/pull/581)
