### ISSUE TITLE
g:tagbar_iconchars handling breaks on latest Neovim

### ISSUE THREAD

**Issue by pappasam** [majutsushi/tagbar#574]
The "termencoding" option has been removed from the latest neovim (0.5.0 master branch). Tagbar expects this variable to exist if `g:tagbar_iconchars` is not set in the user's initialization file. See below for the error message:

![unknown_option_termencoding](https://user-images.githubusercontent.com/3723671/71651019-72e70900-2ce8-11ea-8fad-49cec9c827ac.png)

Temporary fix:

```viml
" init.vim
let g:tagbar_iconchars = ['▶', '▼']
```

**Comment by alerque** [comment]
Thanks for reporting this @pappasam. I've looked into a fix and it seems like its probably safe to assume that if we're on a vim that has dropped the option entirely (note VIM on Windows also dropped this) we can just assume it will work given the other tests.

That being said I'm not actually in a position to test the fix. I use the release version of Neovim and don't have anything on Windows It would be great if we could get people with those platforms to check that my PR works as expected.
