### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by AI-4** [majutsushi/tagbar#595]
I have Ubuntu 18.04.4, neovim v0.2.2, universal-ctags from snap.

https://github.com/majutsushi/tagbar/wiki#markdown Is outdated (works only for Exuberant Ctags? because universal-ctags which is recommended on https://github.com/majutsushi/tagbar uses another config path, and even another syntax? $HOME/ctags.d/default.ctags with examples from tagbar wiki breaks universal-ctags). Despite https://github.com/majutsushi/tagbar/issues/489 I don't see any native markdown support in tagbar. For example, for file test.md
````
# Example #
 ## Part 1 ##
 Test
 ## Part 2 ##
 Just test
````
Tagbar shows message
`" No tags found.`
in neovim config i have
`nmap <F8> :TagbarToggle<CR>
 let g:tagbar_ctags_bin = 'universal-ctags'`
Sorry for my bad English.

**Comment by alerque** [comment]
Please don't use anything at all from the wiki, all of the Markdown related stuff is outdated. If you have a relatively new universal ctags in your path (and _not_ exuberant) you shouldn't need any configuration at all. If you need to force it to find the right ctags (for example if it finds the path to exuberant before universal, then you can set the ctags_bin, but no more. That should be enough to get Markdown tags working.

**Comment by AI-4** [comment]
Thank you.

**Comment by AI-4** [comment]
It is not working.
Is
`let g:tagbar_ctags_bin = 'universal-ctags'`
correct way to set ctags bin? ctags command is ctags from emacs on my system, so i try to force universal-ctags

**Comment by AI-4** [comment]
Full path to universal-ctags
/snap/universal-ctags/current/bin/ctags
solved the issue
