### ISSUE TITLE
How can I execute a command when closing the tagbar?

### ISSUE THREAD

**Issue by danijar** [majutsushi/tagbar#602]
Normal keybindings don't seem to work inside the tagbar. Instead, I use `let g:tagbar_map_close = '<leader>t' to bind a key sequence to the closing the tagbar. However, I would like to also execute another command whenever the tagbar is closed. How could I do that?

To provide a bit more background, I'm using `set laststatus=1` so the status bar is not displayed when editing a single file. However, opening the tagbar means there are two splits and the status bar is shown. This causes the source file to scroll up by one line. I'm compensating for this when opening the tagbar via `nnoremap <leader>t <c-y>:TagbarToggle<cr>`. Because Vim map commands don't seem to apply to the tagbar window, I'm looking for another way to map `<leader>t` in the opened tagbar to `:TagbarClose<br><c-e>`.

**Comment by alerque** [comment]
The vim *filetype* is set to `tagbar` in tagbar panes. You should be abe to use a regular `autocmd` matching on that file type and probably the `BufDelete` event, or even other ones for when it is unfocused or whatever you want.

**Comment by danijar** [comment]
Thanks!

```vim
" Show status bar only when multiple splits are open.
set laststatus=1

" Open or focus tagbar on <leader>t when focusing a file.
nnoremap <leader>t :TagbarOpen j<cr>

" Close tagbar on <leader>t when focusing tagbar.
let g:tagbar_map_close = '<leader>t'

" Compensate for scrolling caused by the status bar.
autocmd FileType tagbar autocmd BufCreate <c-y>
autocmd FileType tagbar autocmd BufDelete <c-e>
```

**Comment by alerque** [comment]
I'm glad you found a solution to your issue, but I can't help but wonder...

If this was just to fix an issue with scroll jitter due to changes in a status bar, wouldn't it be better to fix the status bar? It seems like this solution is brittle and very likely to interfere with future things you do in vim.

**Comment by danijar** [comment]
Yes, I agree. I asked a question about this on StackExchange: https://vi.stackexchange.com/q/25087/3255
