### ISSUE TITLE
Vue support?

### ISSUE THREAD

**Issue by StephenWu5** [majutsushi/tagbar#608]
为什么不支持.vue文件？

**Comment by alerque** [comment]
English please.

**Comment by StephenWu5** [comment]
why not take effect .vue file。

**Comment by alerque** [comment]
If `uctags` supports it and/or there is a third party tag generation tool, we'd be happy to accept a contribution that configured the tags for Vue.

I don't personally use Vue so this will require some other contributor to setup and test.

**Comment by StephenWu5** [comment]
thank you
