### ISSUE TITLE
How to add support async?

### ISSUE THREAD

**Issue by Alexmod** [majutsushi/tagbar#640]
Screenshots:
![async-tag](https://user-images.githubusercontent.com/2562528/89729434-5bba8780-da3e-11ea-8342-c61a49400f58.png)

**Comment by alerque** [comment]
What version of `ctags` are you using?

**Comment by Alexmod** [comment]
Ctags: 5.8
Tagbar Version: 2.7
NVIM v0.3.0
CentOS Linux release 7.7.1908 (Core)

**Comment by alerque** [comment]
I'm sorry, but this isn't enough information to actually identify what you are using. Two main questions:

1. Are you using Exuberant Ctags or Universal Ctags? (The full output of `ctags --version` will narrow this down). If the former, please switch to a new-ish version of Universal Ctags.

2. Tagbar hasn't had versioned / tagged releases for 3 years, but hundreds of things have been fixed and updated. Are you using the latest Git HEAD version (master branch) or actually a 3 year old tagged release?

Additionally (although I don't think this will affect this particular issue) than version of NeoVIM is *really* old and tons and tons of fixes went into the v0.4.x series (now at v0.4.4).

**Comment by alerque** [comment]
I just tested this with the latest versions of this plugin and Universal-Ctags. Async functions in Javascript work just fine. I believe you must be using an outdated ctags, probably the 10-year-old non-maintained exuberant version which we don't actively support any more. Some legacy things work with it, but it has limited language support and hasn't been updated in over a decade. We only support new features with Universal-Ctags or other current versions of tag generators.

Please feel free to comment if you have trouble with this once you're using the latest versions of u-ctags and this plugin ;-)
