### ISSUE TITLE
Error detected while processing function tagbar#ToggleWindow[2].

### ISSUE THREAD

**Issue by arozehnal** [majutsushi/tagbar#641]
I'm using Exuberant Ctags 5.8.
I put in ~.ctags this line for shell scripts:
 --regex-sh=/^[ \t]*(local)?[ \t]*([A-Za-z0-9_-]+)=/\2/v,variable,variables/
    
generated tags file
open script my.ksh
after TagbarToggle
a number of Errors appears

Error detected while processing function tagbar#ToggleWindow[2]..<SNR>56_ToggleWindow[9]..<SNR>56_OpenWindow[43]..<SNR
>56_Init[15]..<SNR>56_AutoUpdate[63]..<SNR>56_ProcessFile[137]..<SNR>60_sortTags[2]..tagbar#sorting#sort[6]..<SNR>64_c
ompare_by_kind:
line    3:
  E716: Key not present in Dictionary: v
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: v
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: v
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: v
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: v
E15: Invalid expression: typeinfo.kinddict[a:tag1.fields.kind] <# typeinfo.kinddict[a:tag2.fields.kind]
E716: Key not present in Dictionary: v

what is wrong?
content of .ctag? plugin?
thank you for your advice

[tagbar_error.zip](https://github.com/majutsushi/tagbar/files/5079171/tagbar_error.zip)

**Comment by alerque** [comment]
Please use Universal Ctags. The Exuberant project hasn't been updated in well over a decade and is causing more and more problems. While we haven't gone out of our way to break compatibility with it on purpose, more and more new languages and features are assuming it and nobody pays us enough to specifically go back and work out kinks with the delinquent Exuberant project.

Also make sure this plugin is up to date while you are at it.

If this is still a problem after switching to uctags please let us know.

**Comment by arozehnal** [comment]
OK, I used last version of Universal Ctags, the plugin is up to date - I installed it today.
I created new tag files, TagbarToggle show  window without error, but it shows only functions, does not show variables. But the variables are in the tag file.
[tags.zip](https://github.com/majutsushi/tagbar/files/5079592/tags.zip)

**Comment by alerque** [comment]
Okay for that last bit since most tagbar configs don't show variables out of the box you might need to tweak your vim init with some custom values changing the default for `g:tagbar_type_sh`. I don't have time myself to investigate what you need to add right now, but you might get some good hints from the Wiki which shows some languages with variable parsing included.

**Comment by alerque** [comment]
This issue has kind of wandered a bit, and the original thing seems to be fixed. If you feel like it maybe add a feature request issue for better default shell parsing. Or if you figured it out maybe you can just directly PR the changes you found useful to the type definition.
