### ISSUE TITLE
Icon wrong encoding

### ISSUE THREAD

**Issue by gzqx** [majutsushi/tagbar#646]
I am not quite sure this is the problem of tagbar but I really don't know why...
I am experiencing 
![wrong icon](https://user-images.githubusercontent.com/24262751/90986883-910abd80-e586-11ea-9f0c-86320070ea24.png)

**Comment by gzqx** [comment]
I have 
```
set encoding=utf-8
```
in `vimrc`

**Comment by alerque** [comment]
This is not a tagbar issue, you have something in your status line that is showing the Git branch currently is use in your project. This is probably airline or something like that, and unrelated to Tagbar. In that configuration you have some special glyphs turned on, probably Powerline or NerdFonts — but you are not using a compatible font in your terminal. It is trying to display the Unicode spmbol Ux16A0 (ᚠ) there, but you aren't using a font in your terminal that supports it.

And this isn't Tagbar related at all.
