### ISSUE TITLE
Tagbar windows opened when typing <Enter> in normal mode

### ISSUE THREAD

**Issue by longmax90** [majutsushi/tagbar#653]
When typing <Enter> in normal mode in Vim with the Tagbar plugin installed, the Tagbar window is opened automatically. I want to disable this functionality. What must I do?

**Comment by alerque** [comment]
I definitely don't see anything like this, I'm guessing you've done something funky with your bindings. If this is still an issue for you posting your RC files somewhere for inspection might help.
